### PR TITLE
Update Rcpp

### PR DESCRIPTION
**Pull request by krlmlr**
to avoid TLS failure for CRAN submission. Also update RcppExports as generated with the most recent version of Rcpp.

CC @hadley @lionel-.

### CODE REVIEW

**Comment by hadley** [comment]
CRAN is fixing the pandoc issue that lead to the badge issue, so I don't think there's a need to change.

**Comment by krlmlr** [comment]
Wouldn't codecov's own badge be preferable to that of shields.io?

**Comment by hadley** [comment]
When I tried it, I got the same TLS problem. We should fix upstream in usethis and then roll out more systematically. Here I think it just adds confusion to this commit (which is mostly about updating Rcpp)

**Comment by krlmlr** [comment]
@hadley: Merged to fix Travis tests, happy to fix as necessary.

**Comment by krlmlr** [comment]
Manual installation of dbplyr doesn't seem to be necessary anymore, reverted in 299aff051.

**Pull request merged**
