### PR TITLE
Fix rchk errors

### PR DESCRIPTION
**Pull request by krlmlr**
https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/dplyr.out

### CODE REVIEW

**Comment by krlmlr** [comment]
Unfortunately, these errors don't show up on rhub (but a new error does). Will merge, submit to CRAN and hope that at least some of the errors disappear.

https://builder.r-hub.io/status/dplyr_0.7.6.tar.gz-649269d951c84f8e98fffaebbcec3a71

**Comment by lionel-** [comment]
With the bools created outside of `create()`?

**Comment by krlmlr** [comment]
A completely different set of errors is reported on rhub, this particular error doesn't show at all on rhub.

@gaborcsardi: We're seeing different output from CRAN's rchk and rhub's rchk. What could be the reason? (Thanks for providing the service!)

**Comment by gaborcsardi** [comment]
Rhub's rchk is older, and I could not update it so far.

**Pull request merged**
