### PR TITLE
Adapt to dev version of glue

### PR DESCRIPTION
**Pull request by krlmlr**
@jimhester: dplyr tests fail with tidyverse/glue@28aa7400, these are the necessary changes. I have seen changes related to NA, but is stripping of space really intended?

### CODE REVIEW

**Comment by jimhester** [comment]
Possibly the space stripping is incorrect, it is tricky to get the trimming to work in all expected cases.

**Comment by krlmlr** [comment]
Thanks. I'll leave this open for now.

**Comment by krlmlr** [comment]
@jimhester: Space are still trimmed in `glue()`, I guess this feature is to stay. Can you please confirm?

``` r
as.character(glue::glue(" "))
#> [1] ""
```

**Comment by jimhester** [comment]
As of https://github.com/tidyverse/glue/commit/ed4b7c0fd142ab72a1afae95b240e7431e50006e single lines are no longer trimmed.

```r
as.character(glue::glue(" "))
#> [1] " "
```

**Comment by krlmlr** [comment]
What about `NA`?

**Comment by jimhester** [comment]
NA was working as intended, any string with an NA should be NA.

One way to fix the example rather than special casing NA is to use

```r
abort(glue(
  "`var` must be a value between {-n} and {n} (excluding zero), not {single_quote(var)}"
))
```

``` r
glue::single_quote(c("foo", NA, "bar"))
#> [1] "'foo'" "NA"    "'bar'"
```

**Comment by krlmlr** [comment]
Don we still need to change the code in dplyr, either way?

**Comment by hadley** [comment]
We're going to roll back this change in glue

**Comment by jimhester** [comment]
It is rolled and on CRAN.

**Pull request closed without merging**
