### PR TITLE
Eliminate dependency on BH

### PR DESCRIPTION
**Pull request by romainfrancois**
I should probably have this somewhere in the 📦 : 

```
$ bcp --boost=/Users/romain/git/RcppCore/bh/inst/include scoped_ptr inst/include/
$ bcp --boost=/Users/romain/git/RcppCore/bh/inst/include shared_ptr inst/include/
$ bcp --boost=/Users/romain/git/RcppCore/bh/inst/include weak_ptr inst/include/
$ bcp --boost=/Users/romain/git/RcppCore/bh/inst/include unordered_map inst/include/
$ bcp --boost=/Users/romain/git/RcppCore/bh/inst/include unordered_set inst/include/
```

### CODE REVIEW

**Comment by romainfrancois** [comment]
I did this as an experiment. It brings >1000 files for these 4 features that we use from boost. 
Should this go to something like a miniboost 📦 perhaps. 

Or is this the time to discuss C++>=11 again ?

**Comment by hadley** [comment]
@jimhester what else do we need for readr? (and elsewhere that we use bh)

I like the idea of a mini-bh package

**Comment by romainfrancois** [comment]
```
romain@purrplex ~/git/tidyverse/readr $ grep -R "boost/" *
src/write.cpp:#include <boost/iostreams/stream.hpp> // stream
src/write_connection.h:#include <boost/iostreams/categories.hpp> // sink_tag
src/write_delim.cpp:#include <boost/iostreams/stream.hpp> // stream
src/boost.h:#include <boost/interprocess/file_mapping.hpp>
src/boost.h:#include <boost/interprocess/mapped_region.hpp>
src/boost.h:#include <boost/container/string.hpp>
src/boost.h:#include <boost/noncopyable.hpp>
src/boost.h:#include <boost/shared_ptr.hpp>
src/boost.h:#include <boost/algorithm/string/predicate.hpp>
src/boost.h:#include <boost/spirit/include/qi.hpp>
src/Collector.h:#include <boost/shared_ptr.hpp>
```

**Comment by krlmlr** [comment]
Is this still valid?

**Comment by romainfrancois** [comment]
We can probably close this in favor of #3674, but if we could make it smaller, then I might like to embark the code directly in dplyr

**Comment by krlmlr** [comment]
Having the same code in _tidylibs_ and _dplyr_ doesn't seem useful to me.?

**Comment by romainfrancois** [comment]
Trying to avoid dependency hell. `tidylibs` could just be a way to extract the relevant subset into 📦s that might need it. This way, the developer of the target 📦 (here dplyr) is in total control of which version of headers are in use.

**Comment by krlmlr** [comment]
Makes sense. It's still at least 350 files (for smart pointers), and 1200 files if we include the hash functional and the `unordered_` classes. Do we really need those, can't we use something that's available from `std::` ?

What do you think about packaging the vendor files in an archive which is unpacked for building, so that they don't clutter the repository?

**Comment by romainfrancois** [comment]
Unfortunately we are stuck with C++ < 11, we'd have to use things from `std::tr1` for unordered, not sure this is universally available.

**Comment by romainfrancois** [comment]
Closing that for now, because I'm relatively confident that we'll use hashing from `vctrs` to deal with #3497 when the time is right.

**Pull request closed without merging**
