### PR TITLE
if_any() and if_all() require both selection and predicate

### PR DESCRIPTION
**Pull request by romainfrancois**

### CODE REVIEW

**Comment by romainfrancois** [comment]
Trying to work around some of the confusion in #5732 by requiring both the tidy selection and the predicate. This probably needs a better error message to explain what is going on, but `filter(if_any(~.x == 39.1))` should not be allowed because the formula will be assumed to be the tidy selection, which causes the confusion of trying to use `where()` in #5732: 

``` r
library(dplyr, warn.conflicts = FALSE)
library(palmerpenguins)

penguins %>% 
  filter(if_any(~.x == 39.1))
#> Error: Problem with `filter()` input `..1`.
#> x if_any() needs both .cols= and .fns=
#> ℹ Input `..1` is `if_any(~.x == 39.1)`.

penguins %>% 
  filter(if_any(everything(), ~.x == 39.1))
#> # A tibble: 1 x 8
#>   species island bill_length_mm bill_depth_mm flipper_length_… body_mass_g sex  
#>   <fct>   <fct>           <dbl>         <dbl>            <int>       <int> <fct>
#> 1 Adelie  Torge…           39.1          18.7              181        3750 male 
#> # … with 1 more variable: year <int>
```

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yutannihilation** [comment]
Sorry if I misunderstand the direction of this pull request, but I think `if_any()` and `if_all()` should NOT require `.fn` because a well-designed data often has some logical columns that itself work as predicates. e.g. 

``` r
library(dplyr, warn.conflicts = FALSE)

patients <- tibble(
  id = 1:3,
  treatment = c(TRUE, FALSE, TRUE), 
  survived = c(TRUE, TRUE, FALSE)
)

patients %>% 
  filter(if_all(where(is.logical)))
#> # A tibble: 1 x 3
#>      id treatment survived
#>   <int> <lgl>     <lgl>   
#> 1     1 TRUE      TRUE
```

<sup>Created on 2021-02-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

(I guess this pull request is going to prohibit this usage, right...?)

**Comment by romainfrancois** [comment]
Oh good point, thanks. I should mark this as a draft pull request, this is mostly a sandbox with some context at this point.

**Comment by romainfrancois** [comment]
scaling down this pr for now so it's just fixing the defaults for .cols = and .fns. Will tackle re-designing the functions later.

**Pull request merged**
