### PR TITLE
#4331 Updated `distinct_if` and `distinct_at` to include .keep_all argument

### PR DESCRIPTION
**Pull request by beansrowning**
As @DaniMori suggested in #4331, this simply tacks the `.keep_all` argument onto the scoped variants of `distinct()`.

I wasn't sure if this was needed (or desired) but I have also wanted a scoped variant of `distinct()` which would allow you the option to keep all columns. Adding it to `distinct_all()` seemed superfluous.  

My use case was reading in many data files where I am appending a `file` column to track provenance. Since my data is very raw, I want to check that there isn't a duplicate observation across two or more files.

Something similar to this:

```r
# Read in many excel files with many columns
# In this case, they're 1 row each
to_process <- dir("<my_dir>", pattern = ".*\\.xlsx$", full.names = TRUE)

# Originally, I assumed one could just do this:
# (but it's not possible due to distinct's mutate() semantics)
raw_data <- lapply(to_process, my_parsing_function) %>%
  bind_rows() %>%
  mutate(file = to_process) %>%
  distinct(-file, .keep_all = TRUE)

# Since I can't do that, I have to do some variation of this 
# (though there are likely better ways):
raw_data <- lapply(to_process, my_parsing_function) %>%
  bind_rows()

distinct_vars <- lapply(names(raw_data), as.name)

raw_data <- raw_data %>%
  mutate(file = to_process) %>%
  distinct(!!!distinct_vars, .keep_all = TRUE)

# Ideally I would just run the scoped version `distinct_at()`
# on all columns, save for file which I append later:
raw_data <- lapply(to_process, my_parsing_function) %>%
  bind_rows() %>%
  mutate(file = to_process) %>%
  distinct_at(vars(-file), .keep_all = TRUE)

# So not ~really~ that big of a deal, but it seems logical ¯\_(ツ)_/¯
```

### CODE REVIEW

**Comment by romainfrancois** [comment]
Still think it makes sense to add it to `distinct_all()` too

**Comment by DaniMori** [comment]
> 
> 
> Still think it makes sense to add it to `distinct_all()` too

I agree that it's superfluous as @beansrowning said, but it wouldn't be the only "superfluous" case to be in `dplyr`.  The most obvious one is `select_all()`.  I can't see a use case where these superfluous functions or parameters would be useful, but there must be some for sure, so they may apply to `distinct_all(..., .keep_all = TRUE)`.

Do they?  I really don't know, probably someone else can state a good case in favor/against it.

**Comment by beansrowning** [comment]
@romainfrancois @DaniMori Fair point, it's reasonable to have it consistent across. 

Added.

**Comment by beansrowning** [comment]
Looks like it fails the check for `distinct_all()` since I made it a recursive default argument.

I'll have to think about it.

**Comment by romainfrancois** [comment]
closes #4331

**Pull request merged**
