### PR TITLE
Expose param `name_repair` in `all_equal()`

### PR DESCRIPTION
**Pull request by salim-b**
Although `all_equal()`'s lifecycle is _questioning_, I dare to propose a minor adjustment to it: Exposing a new parameter `name_repair` which is under the hood passed on to `as_tibble()`.

This allows the user to influence the output messages, cf. #5352

### CODE REVIEW

**Comment by romainfrancois** [comment]
I don't think the change hurts, but again as said in #5352 we no longer think the function should be used. I'll leave it to @Hadley for final. 

You can always write an enhanced version that does the repair before, also `waldo::compare()` does a much more informative job: 

``` r
library(dplyr, warn.conflicts = FALSE)

mtcars2 <- dplyr::rename(mtcars, "m p g" = mpg)

waldo::compare(mtcars, mtcars2)
#> `names(old)[1:4]`: "mpg"   "cyl" "disp" "hp"
#> `names(new)[1:4]`: "m p g" "cyl" "disp" "hp"
#> 
#> `old$mpg` is a double vector (21, 21, 22.8, 21.4, 18.7, ...)
#> `new$mpg` is absent
#> 
#> `old$m p g` is absent
#> `new$m p g` is a double vector (21, 21, 22.8, 21.4, 18.7, ...)

all_equal <- function(target, current, ..., .name_repair = c("check_unique", "unique", "universal", "minimal")) {
  dplyr::all_equal(
    as_tibble(target, .name_repair = .name_repair), 
    as_tibble(current, .name_repair = .name_repair), 
    ...
  )
}
all_equal(mtcars, mtcars2, .name_repair = "unique")
#> [1] "not compatible: \n- Cols in y but not x: `m p g`.\n- Cols in x but not y: `mpg`.\n"
```

<sup>Created on 2020-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by salim-b** [comment]
Thanks @romainfrancois for the hint to `waldo::compare()`. It does a great job, no doubt! But it (currently) doesn't provide **any means to ignore row and/or column order** (which I need). Do you happen to know an easy approach to extending `waldo::compare()` to provide this additional functionality?

> I don't think the change hurts, but again as said in #5352 we no longer think the function should be used.

Glad to hear. I've added a NEWS bullet in https://github.com/tidyverse/dplyr/pull/5565/commits/cef30f1cbb6507bf3d0f68d6283c98098218557f explicitly mentioning the newer `waldo::compare()` etc., so there won't be any misunderstandings :) I hope that's fine.

**Comment by hadley** [comment]
Yeah, I don't think we should be changing this function. I'd suggest using `waldo::compare()` after manually sorting the rows/cols.

**Comment by salim-b** [comment]
> (...) after manually sorting the rows/cols.

💡! So obvious... I'm really tired, I guess 🙈😂 Thanks!

**Pull request closed without merging**
