### PR TITLE
rename() uses eval_rename(name_spec=)

### LINKED ISSUE #5207: dplyr::rename with fixed new-names and old-names given by length-1 named vectors gives wrong names
A one-line reprex of this behavior is:

``` r
dplyr::rename(data.frame(old = 1), new = c(dud = "old"))
#>   new...dud
#> 1         1
```

This is an issue if we have a function where data.frames with myriad names have their names changed to certain "standard" names. In the case below, I have a standard column-name `foo`, but a data.frame's called it `bar` instead, so we call the following function to give it the standard name

``` r
standardize <- function(df, fooName) {
  dplyr::rename(df, foo = !!fooName)
}

standardize(data.frame(bar = 1), "bar")
#>   foo
#> 1   1
```

<sup>Created on 2020-05-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This works just fine.

However, if, for whatever reason, the value passed to `fooName` is a length-1 named vector, we get the behavior shown at the start:

``` r
name <- c(buzz = "bar")
standardize(data.frame(bar = 1), name)
#>   foo...buzz
#> 1          1
```

The vector's name is clumsily suffixed to the desired name with an ellipsis. Is this expected behavior? I'm currently solving this by using `foo = unname(fooName)`, which works, but wonder if this is just a bug.

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #5207 

``` r
dplyr::rename(data.frame(old = 1), new = c(dud = "old"))
#>   dud
#> 1   1
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Or should this an error to use the form `new = c(...)` ?

### CODE REVIEW

**Comment by romainfrancois** [comment]
🤔 actually maybe `"{outer}"` makes more sense, considering the initial example in #5207: 

``` r
library(dplyr, warn.conflicts = FALSE)

standardize <- function(df, fooName) {
  dplyr::rename(df, foo = !!fooName)
}

standardize(data.frame(bar = 1), "bar")
#>   foo
#> 1   1
name <- c(buzz = "bar")
standardize(data.frame(bar = 1), name)
#>   foo
#> 1   1
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
I think the names should be determined from the inner vector, and supplying both outer and inner names should be an error. Also we should probably fix the default in tidyselect itself (release incoming this week).

**Comment by romainfrancois** [comment]
In the meantime: 

``` r
dplyr::rename(data.frame(old = 1), new =  c(dud = "old"))
#> Error: Problem with `rename()` input `new`
#> x Input `new` is a named vector
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
I think this is too strict a breaking change. We should allow named inner vectors without outer names.

**Comment by romainfrancois** [comment]
I got this for free somehow: 

``` r
dplyr::rename(data.frame(old = 1), c(dud = "old"))
#>   dud
#> 1   1
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
I see

```r
data.frame(x = 1, y = 2) %>%
  rename(quux = !!c(foo = "x", bar = "y"))
#> Error: nms %in% c("i", "x", "") are not all TRUE
```

This is because vctrs returns the recycled outer names:

```r
vec_c(foo = c(x = 1, y = 2), .name_spec = ~ print(list(.x, .y)))
#> [[1]]
#> [1] "foo" "foo"
#>
#> [[2]]
#> [1] "x" "y"
#>
#> Error: `.name_spec` must return a character vector.
```

I see this comment in the vctrs source code:

```c
  // Recycle `outer` so specs don't need to refer to both `outer` and `inner`
```

However now I wonder why we don't recycle the return values. I have opened https://github.com/r-lib/vctrs/issues/1099

And I also opened an upstream tidyselect issue: https://github.com/r-lib/tidyselect/issues/197

Since it's a bit tricky, I suggest we just leave the current behaviour for now, so we don't have multiple implementations lying around?

**Comment by romainfrancois** [comment]
Now seeing this in master branch. 

``` r
library(dplyr, warn.conflicts = FALSE)
data.frame(x = 1, y = 2) %>%
  rename(quux = !!c(foo = "x", bar = "y"))
#>   quux...foo quux...bar
#> 1          1          2
```

<sup>Created on 2021-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by romainfrancois** [comment]
I think we can close this pull request now: 

``` r
dplyr::rename(data.frame(old = 1), new = c(dud = "old"))
#>   new...dud
#> 1         1
```

<sup>Created on 2021-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Pull request closed without merging**
