### PR TITLE
bind_rows() puts "id" first

### LINKED ISSUE #4876: bind_rows() now puts id at end
Should be at beginning, like this reprex:

``` r
dplyr::bind_rows(list(x = data.frame(a = 1)), .id = "id")
#>   id a
#> 1  x 1
```

<sup>Created on 2020-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #4876 

depends on https://github.com/r-lib/vctrs/issues/855

### CODE REVIEW

**Comment by romainfrancois** [comment]
Should I try to adapt the tests so that this works with older vctrs ?

**Comment by romainfrancois** [comment]
yeah should be ok

**Comment by hadley** [comment]
(However, we probably should've bumped the version of vctrs, and then bumped the requirement in dplyr, just to make life a little easier for those people living on the edge)

**Comment by lionel-** [comment]
Good point, I just bumped to 0.2.99.9006 @romainfrancois

**Pull request merged**
