### PR TITLE
WIP: Evaluation based hybrid evaluation

### PR DESCRIPTION
**Pull request by romainfrancois**
This is far from ready, but having it as a PR makes it easier to help me. Struggling with data mask in the `DataMask.h` file 😬.

### CODE REVIEW

**Comment by romainfrancois** [comment]
So now I have: 

`env` -> `hybrids` (for the functions) -> `bindings` (for the columns)

With this function: 

```r
ntile_h <- function(x, n) {
  tibble(x = x) %>%
    mutate(y = ntile(x, n)) %>%
    pull(y)
}
```

The `n` in the `hybrids` environment of the data mask is found before the `n` argument of the function, which supposedly lives in `env`. 

Can I do something about it @lionel- ?

**Comment by krlmlr** [comment]
Any reason you don't do env -> bindings -> hybrids instead?

**Comment by romainfrancois** [comment]
Because columns should be matched first: 

```
> tibble( n = 1:3 ) %>% summarise(sum(n))
# A tibble: 1 x 1
  `sum(n)`
     <int>
1        6
```

**Comment by romainfrancois** [comment]
I guess what I want is to mask `n` from the `dplyr` namespace but not earlier.

Or maybe I can make `dplyr::n` lookup for information somewhere I can alter. This way I don't even need to mask it. I'll try that.

**Comment by romainfrancois** [comment]
Yes, I guess our comments crossed. I'll try that. This might give us an opportunity to update the message for something more useful

"This function should not be called directly"

**Comment by lionel-** [comment]
> One way to solve it would be to implement dplyr::n() and the other functions in a way that they "just work"

Agreed. You could perhaps install a hidden flag in the data mask. If present (looking in the parent frame from the hybrided functions) you call into the hybrid routines.

**Comment by romainfrancois** [comment]
Maybe something like this 

```r
no_data_context <- new.env(parent = emptyenv())
makeActiveBinding("..group_size", function() abort("not in a data context"), no_data_context)
makeActiveBinding("..group_number", function() abort("not in a data context"), no_data_context)

data_context <- new.env(parent = no_data_context)
n <- function() {
  get("..group_size", envir = data_context)
}
```

And then the `DataMask` class manages `data_context`

**Comment by romainfrancois** [comment]
🤔 not sure this is enough for cases like a `mutate( x = map(x, ~mutate(x, ...) )`

**Comment by krlmlr** [comment]
How about just:

```r
.context <- new.env(parent = emptyenv()) # what's the rlang equivalent again?

n <- function() {
  ret <- .context$n
  if (is_empty(ret)) abort("A better error message than before.")
  ret[[1]]
}
```

In recursive calls, `.context$n` acts like a stack.

**Comment by romainfrancois** [comment]
That looks like a lot of code for something as simple as `n`, and I feel that an ancestry of environments is more suited to deal with such as stack. 

Does an environment know its childs ?

**Comment by lionel-** [comment]
> Does an environment know its childs ?

It doesn't.

How about just looking at the number of rows in `.data`, taken from the parent frame? This should work with the grouped case I think?

**Comment by hadley** [comment]
Can we continue to use bindrcpp in this PR and explore alternative strategies for binding column names in future work?

**Comment by romainfrancois** [comment]
We can. I’ll bring back active bindings. This is fairly secluded in the DataMask_bindings class. 



The approach I explore with promises would make it possible to simplify further some internals. Right now the C++ class (e.g GroupedSubsets) that is reached from the active bindings has to manage whether the subset has been resolved and hold it. 

Relying on promises makes it simpler to let R deal with that. 

For each variable: 
 - first install a promise to evaluate x[i]
 - if the promise has been forced, which is easy and cheap to check, we know that the expression needs this variable, so we can install the subset directly for each group (currently i install another promise though)
- if not, it means the variable is not needed, so i replace i in the promise code, in case it is needed by another group. 

I’ll stash that somewhere and switch to active bindings via bindrcpp.

**Comment by romainfrancois** [comment]
I resurrected the active bindings implementation. The `DataMask_bindings<>` template class forwards management of the bindings environment to an implementation class: 

```cpp
template <typename Data>
class DataMask_bindings {
public:
  typedef typename Data::slicing_index Index ;
  typedef LazySplitSubsets<Data> Subsets;

  DataMask_bindings(SEXP parent_env, Subsets& subsets) :
    impl(parent_env, subsets)
  {}

  void update(const Index& indices) {
    impl.update(indices);
  }

  inline operator SEXP() {
    return impl;
  }

private:
  DataMask_bindings_active<Data> impl ;
};
```

Currently, this is `DataMask_bindings_active` that is inspired on previous code. I've left the `DataMask_bindings_promises` template if we want to replace it. 

Bringing it back was not easy and not fun, and I'm still not sure I understand it 💯 .

**Comment by romainfrancois** [comment]
superseded

**Pull request closed without merging**
