### PR TITLE
WIP: Evaluation based hybrid evaluation - promises version

### PR DESCRIPTION
**Pull request by romainfrancois**
Similar to #3639 but simplified further with implementation of DataMask with promises and consequences this has on simplifying further the code.

### CODE REVIEW

**Comment by krlmlr** [comment]
Did we agree to discuss the promises code separately? It seems that the PR switches to promises, are they clearly better than active bindings?

I missed your earlier comment in https://github.com/tidyverse/dplyr/pull/3639#issuecomment-395884928. It would be great to be able to compare two alternative implementations against each other. I also missed writing up the logic behind the implementation with active bindings, maybe that would have helped.

**Comment by romainfrancois** [comment]
I have two branches. One with ab, one with promises. So that we can compare.

**Comment by krlmlr** [comment]
Got it. I see that both PRs are related, but this PR does contain some extra commits. I have no idea what these commits do, but for a fair comparison the differences between the branches should be minimal.

In my fork, I have rearranged the one commit that removes the active bindings based implementation, 3ed7c5c80fa42d48848f5a154b65848711703f4f, to the end, so that this is the only difference between the two branches. (I had to resolve one very minor conflict.)

Branches:

- https://github.com/krlmlr/dplyr/tree/hybrid-remake
- https://github.com/krlmlr/dplyr/tree/hybrid-remake-promises

I'll look at the code in action too.

**Comment by romainfrancois** [comment]
with the promise impl, the subsetting is done with r code, so many classes become irrelevant. 

These commit prune the repo from potentially obsolete classes. 

This still has some errors that i will deal with at some point. 

I’m now focusing on step 2 of the hybrid refactoring in a branch that follows the other one. 

We can probably merge or at least focus on discussing the active bindings based implementation for now.

**Comment by krlmlr** [comment]
Could we also do the subsetting in R with active bindings?

Are you suggesting to merge #3639 first and take it from there?

**Comment by romainfrancois** [comment]
superseded

**Pull request closed without merging**
