### PR TITLE
across() gains .call= so that we can control which call governs the caching

### LINKED ISSUE #5782: Suprising behaviour of if_any() inside case_when
I am not sure if I am doing something wrong, but If that is the case I cannot see what in next reproducible example:
```r
data <- structure(list(x = c(1, 1, -1, -1, -1, -1, 1, -1, -1, -1, 1, 
-1, -1, -1, -1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, -1, -1, -1, 
-1, -1), y = c(-1, -1, 1, 1, 2, 1, -1, 1, 1, 1, -1, 1, 1, 1, 
1, -1, 1, -1, 1, 1, 2, -1, 1, -1, 1, 1, 1, 1, 1, 1)), row.names = c(NA, 
-30L), class = c("tbl_df", "tbl", "data.frame"))

data %>%
    mutate(dich = case_when(if_any(c(x, y), function(.x) {.x == 1}) ~ "green",
                             x==2 | y==2 ~ "blue",
                             TRUE ~ NA_character_)) %>%
    pull(dich) %>% table(useNA = "ifany")
blue green 
    2    28 

# but

data %>%
    mutate(dich = case_when(if_any(c(x, y), function(.x) {.x == 1}) ~ "green",
                             if_any(c(x, y), function(.x) {.x == 2}) ~ "blue",
                             TRUE ~ NA_character_)) %>%
    pull(dich) %>% table(useNA = "ifany")
green  <NA> 
   28     2 
```

Thank you!

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #5782

``` r
library(dplyr, warn.conflicts = FALSE)

df <- data.frame(
  x = 1:3
)
df %>% mutate(
  y1 = case_when(
    if_any(everything(), ~ . >= 3) ~ "big",
    if_any(everything(), ~ . >= 2) ~ "medium",
    TRUE ~ "small"
  ),
  y2 =  case_when(
    x >= 3 ~ "big",
    x >= 2 ~ "medium",
    TRUE ~ "small"
  )
)
#>   x     y1     y2
#> 1 1  small  small
#> 2 2 medium medium
#> 3 3    big    big
```

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by romainfrancois** [comment]
Another way would be to not call `across()` from these altogether. But still, there needs some way to control, the `across()` call itself can't always disambiguate, i.e.

``` r
library(dplyr, warn.conflicts = FALSE)
times <- function(cols, multiplier = 1) {
  across({{ cols }}, function(x) {
    print(multiplier)
    x * multiplier
  }, .call = sys.call())
}
data.frame(x = 1) %>% 
  summarise(
    three = times(x, 1)$x + times(x, 2)$x
  )
#> [1] 1
#> [1] 2
#>   three
#> 1     3
```

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
Something related that this does not solve is that since the `fns` are being cached as well, if the `.call` looks the same then we can get the wrong results if the `fns` bindings have changed. This is sort of what is happening in the `times` example, because the anonymous function isn't being regenerated with a new `multiplier`

``` r
library(dplyr)

data.frame(x = c(1, 2)) %>%
  summarise(
    y = {
      fn <- sum
      print(across(everything(), fn))
      fn <- mean
      print(across(everything(), fn))
      1
    }
  )
#> # A tibble: 1 x 1
#>       x
#>   <dbl>
#> 1     3
#> # A tibble: 1 x 1
#>       x
#>   <dbl>
#> 1     3
#>   y
#> 1 1
```

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by romainfrancois** [comment]
One resolution could be to settle with the fact that we have the instrumented `top_across()` thing to deal with the special case where the `across()` call is top level, and drop the caching mechanism. 

But it feels like paying a high price so that these esoteric `across()` calls are supported.

**Comment by romainfrancois** [comment]
Merging this for now so that `if_any()` and `if_all()` do work, i.e. fix the problem raised in #5782 

Function that call `across()` and want to disambiguate would have to use the `.call=` argument, that seems good enough compromise for now.

**Pull request merged**
