### PR TITLE
Avoid reexporting deprecated APIs

### PR DESCRIPTION
**Pull request by krlmlr**
Based off of v1.0.7. Won't merge, adding revdepcheck results here.

### CODE REVIEW

**Comment by krlmlr** [comment]
We can remove at least two: `lst_()` and `frame_data()` . The `data_frame_()` function is used only by googlesheets.

**Comment by romainfrancois** [comment]
Looks like this only would affect `googlesheets` so I've sent a pull request here: https://github.com/jennybc/googlesheets/pull/403

**Comment by romainfrancois** [comment]
Is this a duplicate of #6059 ?

**Comment by DavisVaughan** [comment]
Duplicate of #6059

**Pull request closed without merging**
