### PR TITLE
Using 1-based indices in grouping metadata

### PR DESCRIPTION
**Pull request by romainfrancois**
```
> tibble( x = 1:4, g = rep(1:2, each = 2)) %>% group_by(g) %>% group_rows()
[[1]]
[1] 1 2

[[2]]
[1] 3 4
```

### CODE REVIEW

**Comment by hadley** [comment]
Is this going to break tidyr? If so, we need to think a bit about release planning.

**Comment by romainfrancois** [comment]
I'll have a look at tidyr, how much does it use the internal structure of grouped data frames ?

**Comment by romainfrancois** [comment]
This is a dangerous off by one kind of PR, and it was a bit too easy so I need to carefully check if there are no other off by one problems lurking around.

**Comment by romainfrancois** [comment]
`tidyr` seems immune to these changes: 

```
OK:       323
Failed:   0
Warnings: 0
Skipped:  0
```

Between #3489 and this, I guess we can do a rev dev check soon, there are probably 📦 that depend on the previous structure of attributes.

**Comment by krlmlr** [comment]
These segfaults are gone now with 9584596.

**Pull request merged**
