### PR TITLE
using compat-lifecycle

### PR DESCRIPTION
**Pull request by romainfrancois**
@lionel- would you have a look please ?

### CODE REVIEW

**Comment by lionel-** [comment]
I think it's too harsh to deprecate the underscore functions without a soft-deprecation cycle. Also should we [retire](https://www.tidyverse.org/lifecycle/#retired) them instead of soft-deprecating them? i.e. maintain these functions undefinitely as long as they are not a maintenance burden.

**Comment by romainfrancois** [comment]
Were they not soft deprecated already ?

**Comment by lionel-** [comment]
> Were they not soft deprecated already ?

Not in the compat-lifecycle sense. They did not warn users calling from the global env nor developers testing their packages. These soft warnings are meant to ease the deprecation process.

**Comment by romainfrancois** [comment]
I see. I'll move them to soft deprecated then. Does that mean #4043 should be reopen ?

**Comment by hadley** [comment]
No, because they are soft deprecated, and we should be steering people away from them.

**Pull request merged**
