### PR TITLE
Make Code of Conduct visible to github

### PR DESCRIPTION
**Pull request by filipefilardi**
I change the name of your conduct.md to CODE_OF_CONDUCT.md.

That way, github can understand [where is your code of conduct](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/) and show it in [dplyr community profile](https://github.com/tidyverse/dplyr/community).

Hope this change make sense for you guys and doesn't sound anoying =D

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks!

**Comment by krlmlr** [comment]
Thanks, it pops up when filing a new issue.

screenshot from 2018-06-07 15-10-38

What about the other items?

screenshot from 2018-06-07 15-11-30

**Comment by filipefilardi** [comment]
I'm not sure why [ISSUE_TEMPLATE.md](https://github.com/tidyverse/dplyr/blob/master/ISSUE_TEMPLATE.md) isn't in community profile.

> To add an Issue template to a repository create a file called ISSUE_TEMPLATE in the root directory. A file extension is optional, but Markdown files (.md) are supported.

from: https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

Dplyr repository doesn't have a pull request and contributing file yet.

**Comment by krlmlr** [comment]
Thanks for the heads-up. I wonder if we should/need to move these files to `.github/` ?

**Comment by batpigandme** [comment]
I think they are in the new usethis — hold off on that, and we'll use it. @filipefilardi since this PR has been merged, can you please submit as an issue?

**Comment by filipefilardi** [comment]
You're welcome

I think it will solve the problem but i don't think is necessary. Other option is rename it to `ISSUE_TEMPLATE` but you will loose markdown sintax.

What happens if you press `add` in issue templates?

@batpigandme sure!  Should i open about CI problem only or CI + issue_template visibility problem?

**Comment by batpigandme** [comment]
Always one issue per prob, and best to keep them outside the PRs to avoid confusion. No need wrt to the latter, I believe. Should be fixed with https://github.com/tidyverse/dplyr/pull/3648.

**Comment by batpigandme** [comment]
@filipefilardi 
> What happens if you press add in issue templates?
To keep things consistent across the tidyverse, we're setting this up through usethis.

**Comment by filipefilardi** [comment]
Thanks @batpigandme

**Pull request merged**
