### PR TITLE
strict parameter for select_vars (related to #2981)

### PR DESCRIPTION
**Pull request by twolodzko**
This commit introduces `strict` parameter in `select_vars` function (as discussed in #2981). Instead of using `eval_tidy`, `eval_safely` function is introduced that uses `safely(eval_tidy)` instead of it when `strict = FALSE`. For everything to work, next the `NULL` variables (i.e. nonexistent) are dropped from `ind_list` and `names2(quos)`.

### CODE REVIEW

**Comment by lionel-** [comment]
These functions are now living in the tidyselect package.

I think we'll want to catch only the "symbol not found" errors and to do this cleanly will require some changes in R core. Catching and parsing the error message could be a stopgap for compatibility with old releases.

**Comment by twolodzko** [comment]
@lionel- OK, but the `strict = FALSE` default would not produce any compatibility issues.

**Comment by lionel-** [comment]
Thanks for the PR @twolodzko. We've reimplemented it in tidyselect with a different approach.

**Comment by lionel-** [comment]
Here is the relevant commit if you want to check it out: https://github.com/tidyverse/tidyselect/commit/14356f23da0a079af38bcdff4c7824edfab6459b

**Pull request closed without merging**
