### PR TITLE
row wise specific error bullets

### PR DESCRIPTION
**Pull request by romainfrancois**
``` r
library(dplyr, warn.conflicts = FALSE)

tibble(x = 1, y = c(1, 2, 2), z = runif(3)) %>%
  rowwise() %>%
  summarise(a = lm(y ~ x))
#> Error: `summarise()` argument `a` must be a vector.
#> ℹ `a` is `lm(y ~ x)`.
#> ℹ The error occured in row 1.
#> x `a` must be a vector, not a list.
#> ℹ Did you mean: `a = list(lm(y ~ x))` ?

data.frame(x = c(2, 2, 3, 3)) %>%
  rowwise() %>%
  mutate(int = 1:5)
#> Error: `mutate()` argument `int` must be recyclable.
#> ℹ `int` is `1:5`.
#> ℹ The error occured in row 1.
#> x `int` can't be recycled to size 1.
#> ℹ `int` must be size 1, not 5.
#> ℹ Did you mean: `int = list(1:5)` ?
```

<sup>Created on 2020-01-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

### CODE REVIEW

**Comment by romainfrancois** [comment]
closes #4780

**Comment by jeffreypullin** [comment]
Hi, just looking at this PR because it linked to the issue I opened. 

I may be wrong but shouldn't the fourth line in the error in the first example read something like: 

```#> x `a` must be a vector, not an object of class `lm`.```

instead of saying that `a` should not be a list?

All the best!

**Comment by romainfrancois** [comment]
Maybe we should be using something else than `as_friendly_type()`: 

``` r
dplyr:::as_friendly_type(typeof(lm(c(1, 2) ~ c(2, 3))))
#> [1] "a list"
```

<sup>Created on 2020-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by romainfrancois** [comment]
Updated to use `friendly_type_of()` instead:

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(x = 1, y = c(1, 2, 2), z = runif(3)) %>%
  rowwise() %>%
  summarise(a = lm(y ~ x))
#> Error: `summarise()` argument `a` must be a vector.
#> ℹ `a` is `lm(y ~ x)`.
#> ℹ The error occured in row 1.
#> x `a` must be a vector, not a `lm` object.
#> ℹ Did you mean: `a = list(lm(y ~ x))` ?
```

<sup>Created on 2020-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Pull request merged**
