### PR TITLE
Move deprecation down to method, not generic slice_()

### LINKED ISSUE #5222: Confusing deprecation warning for slice when applied to vector or list
Applying `slice()` to a non-data frame gives an error, which makes sense. However, the deprecation warning is confusing I think, as it says "use `slice()` instead" which is already what I'm using.

I'll provide two separate reprexes for a vector and a list so that the deprecation message is printed in both:

- character vector:

``` r
suppressMessages(library(dplyr))
packageVersion("dplyr")
#> [1] '0.8.99.9002'

v <- c("hi", "hello")

v %>% slice(1)
#> Warning: `slice_()` is deprecated as of dplyr 0.7.0.
#> Please use `slice()` instead.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
#> Error in UseMethod("slice_"): no applicable method for 'slice_' applied to an object of class "character"
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

- list:

``` r
suppressMessages(library(dplyr))
packageVersion("dplyr")
#> [1] '0.8.99.9002'

l <- list("hi", "hello")

l %>% slice(1)
#> Warning: `slice_()` is deprecated as of dplyr 0.7.0.
#> Please use `slice()` instead.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
#> Error in UseMethod("slice_"): no applicable method for 'slice_' applied to an object of class "list"
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #5222 

``` r
library(dplyr, warn.conflicts = FALSE)

c("hi", "hello") %>% slice(1)
#> Error in UseMethod("slice_"): no applicable method for 'slice_' applied to an object of class "character"
list("hi", "hello") %>% slice(1)
#> Error in UseMethod("slice_"): no applicable method for 'slice_' applied to an object of class "list"
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.0 (2020-04-24)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Paris                
#>  date     2020-05-11                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version     date       lib source                        
#>  assertthat    0.2.1       2019-03-21 [1] CRAN (R 4.0.0)                
#>  backports     1.1.6       2020-04-05 [1] CRAN (R 4.0.0)                
#>  callr         3.4.3       2020-03-28 [1] CRAN (R 4.0.0)                
#>  cli           2.0.2       2020-02-28 [1] CRAN (R 4.0.0)                
#>  crayon        1.3.4.9000  2020-04-27 [1] Github (r-lib/crayon@dcf6d44) 
#>  desc          1.2.0       2018-05-01 [1] CRAN (R 4.0.0)                
#>  devtools      2.3.0       2020-04-10 [1] CRAN (R 4.0.0)                
#>  digest        0.6.25      2020-02-23 [1] CRAN (R 4.0.0)                
#>  dplyr       * 0.8.99.9002 2020-05-11 [1] local                         
#>  ellipsis      0.3.0       2019-09-20 [1] CRAN (R 4.0.0)                
#>  evaluate      0.14        2019-05-28 [1] CRAN (R 4.0.0)                
#>  fansi         0.4.1       2020-01-08 [1] CRAN (R 4.0.0)                
#>  fs            1.4.1       2020-04-04 [1] CRAN (R 4.0.0)                
#>  generics      0.0.2       2018-11-29 [1] CRAN (R 4.0.0)                
#>  glue          1.4.0       2020-04-03 [1] CRAN (R 4.0.0)                
#>  highr         0.8         2019-03-20 [1] CRAN (R 4.0.0)                
#>  htmltools     0.4.0       2019-10-04 [1] CRAN (R 4.0.0)                
#>  knitr         1.28        2020-02-06 [1] CRAN (R 4.0.0)                
#>  lifecycle     0.2.0       2020-03-06 [1] CRAN (R 4.0.0)                
#>  magrittr      1.5         2014-11-22 [1] CRAN (R 4.0.0)                
#>  memoise       1.1.0       2017-04-21 [1] CRAN (R 4.0.0)                
#>  pillar        1.4.4       2020-05-05 [1] CRAN (R 4.0.0)                
#>  pkgbuild      1.0.8       2020-05-07 [1] CRAN (R 4.0.0)                
#>  pkgconfig     2.0.3       2019-09-22 [1] CRAN (R 4.0.0)                
#>  pkgload       1.0.2       2018-10-29 [1] CRAN (R 4.0.0)                
#>  prettyunits   1.1.1       2020-01-24 [1] CRAN (R 4.0.0)                
#>  processx      3.4.2       2020-02-09 [1] CRAN (R 4.0.0)                
#>  ps            1.3.2       2020-02-13 [1] CRAN (R 4.0.0)                
#>  purrr         0.3.4       2020-04-17 [1] CRAN (R 4.0.0)                
#>  R6            2.4.1       2019-11-12 [1] CRAN (R 4.0.0)                
#>  Rcpp          1.0.4.6     2020-04-09 [1] CRAN (R 4.0.0)                
#>  remotes       2.1.1       2020-02-15 [1] CRAN (R 4.0.0)                
#>  rlang         0.4.6       2020-05-02 [1] CRAN (R 4.0.0)                
#>  rmarkdown     2.1         2020-01-20 [1] CRAN (R 4.0.0)                
#>  rprojroot     1.3-2       2018-01-03 [1] CRAN (R 4.0.0)                
#>  sessioninfo   1.1.1       2018-11-05 [1] CRAN (R 4.0.0)                
#>  stringi       1.4.6       2020-02-17 [1] CRAN (R 4.0.0)                
#>  stringr       1.4.0       2019-02-10 [1] CRAN (R 4.0.0)                
#>  testthat      2.3.2       2020-03-02 [1] CRAN (R 4.0.0)                
#>  tibble        3.0.1       2020-04-20 [1] CRAN (R 4.0.0)                
#>  tidyselect    1.0.0       2020-01-27 [1] CRAN (R 4.0.0)                
#>  usethis       1.6.1.9000  2020-05-05 [1] Github (r-lib/usethis@4487260)
#>  vctrs         0.3.0       2020-05-07 [1] Github (r-lib/vctrs@5b71d88)  
#>  withr         2.2.0       2020-04-20 [1] CRAN (R 4.0.0)                
#>  xfun          0.13        2020-04-13 [1] CRAN (R 4.0.0)                
#>  yaml          2.2.1       2020-02-01 [1] CRAN (R 4.0.0)                
#> 
#> [1] /Users/romainfrancois/.R/library/4.0
#> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

### CODE REVIEW

**Comment by romainfrancois** [comment]
Do we however still need `slice.default()` : 

```r
#' @export
slice.default <- function(.data, ..., .preserve = FALSE) {
  slice_(.data, .dots = compat_as_lazy_dots(...))
}
```

**Comment by romainfrancois** [comment]
If I remove `slice.default()` I get this: 

``` r
library(dplyr, warn.conflicts = FALSE)

c("hi", "hello") %>% slice(1)
#> Error in UseMethod("slice"): no applicable method for 'slice' applied to an object of class "character"
list("hi", "hello") %>% slice(1)
#> Error in UseMethod("slice"): no applicable method for 'slice' applied to an object of class "list"
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.0 (2020-04-24)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Paris                
#>  date     2020-05-11                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version     date       lib source                        
#>  assertthat    0.2.1       2019-03-21 [1] CRAN (R 4.0.0)                
#>  backports     1.1.6       2020-04-05 [1] CRAN (R 4.0.0)                
#>  callr         3.4.3       2020-03-28 [1] CRAN (R 4.0.0)                
#>  cli           2.0.2       2020-02-28 [1] CRAN (R 4.0.0)                
#>  crayon        1.3.4.9000  2020-04-27 [1] Github (r-lib/crayon@dcf6d44) 
#>  desc          1.2.0       2018-05-01 [1] CRAN (R 4.0.0)                
#>  devtools      2.3.0       2020-04-10 [1] CRAN (R 4.0.0)                
#>  digest        0.6.25      2020-02-23 [1] CRAN (R 4.0.0)                
#>  dplyr       * 0.8.99.9002 2020-05-11 [1] local                         
#>  ellipsis      0.3.0       2019-09-20 [1] CRAN (R 4.0.0)                
#>  evaluate      0.14        2019-05-28 [1] CRAN (R 4.0.0)                
#>  fansi         0.4.1       2020-01-08 [1] CRAN (R 4.0.0)                
#>  fs            1.4.1       2020-04-04 [1] CRAN (R 4.0.0)                
#>  generics      0.0.2       2018-11-29 [1] CRAN (R 4.0.0)                
#>  glue          1.4.0       2020-04-03 [1] CRAN (R 4.0.0)                
#>  highr         0.8         2019-03-20 [1] CRAN (R 4.0.0)                
#>  htmltools     0.4.0       2019-10-04 [1] CRAN (R 4.0.0)                
#>  knitr         1.28        2020-02-06 [1] CRAN (R 4.0.0)                
#>  lifecycle     0.2.0       2020-03-06 [1] CRAN (R 4.0.0)                
#>  magrittr      1.5         2014-11-22 [1] CRAN (R 4.0.0)                
#>  memoise       1.1.0       2017-04-21 [1] CRAN (R 4.0.0)                
#>  pillar        1.4.4       2020-05-05 [1] CRAN (R 4.0.0)                
#>  pkgbuild      1.0.8       2020-05-07 [1] CRAN (R 4.0.0)                
#>  pkgconfig     2.0.3       2019-09-22 [1] CRAN (R 4.0.0)                
#>  pkgload       1.0.2       2018-10-29 [1] CRAN (R 4.0.0)                
#>  prettyunits   1.1.1       2020-01-24 [1] CRAN (R 4.0.0)                
#>  processx      3.4.2       2020-02-09 [1] CRAN (R 4.0.0)                
#>  ps            1.3.2       2020-02-13 [1] CRAN (R 4.0.0)                
#>  purrr         0.3.4       2020-04-17 [1] CRAN (R 4.0.0)                
#>  R6            2.4.1       2019-11-12 [1] CRAN (R 4.0.0)                
#>  Rcpp          1.0.4.6     2020-04-09 [1] CRAN (R 4.0.0)                
#>  remotes       2.1.1       2020-02-15 [1] CRAN (R 4.0.0)                
#>  rlang         0.4.6       2020-05-02 [1] CRAN (R 4.0.0)                
#>  rmarkdown     2.1         2020-01-20 [1] CRAN (R 4.0.0)                
#>  rprojroot     1.3-2       2018-01-03 [1] CRAN (R 4.0.0)                
#>  sessioninfo   1.1.1       2018-11-05 [1] CRAN (R 4.0.0)                
#>  stringi       1.4.6       2020-02-17 [1] CRAN (R 4.0.0)                
#>  stringr       1.4.0       2019-02-10 [1] CRAN (R 4.0.0)                
#>  testthat      2.3.2       2020-03-02 [1] CRAN (R 4.0.0)                
#>  tibble        3.0.1       2020-04-20 [1] CRAN (R 4.0.0)                
#>  tidyselect    1.0.0       2020-01-27 [1] CRAN (R 4.0.0)                
#>  usethis       1.6.1.9000  2020-05-05 [1] Github (r-lib/usethis@4487260)
#>  vctrs         0.3.0       2020-05-07 [1] Github (r-lib/vctrs@5b71d88)  
#>  withr         2.2.0       2020-04-20 [1] CRAN (R 4.0.0)                
#>  xfun          0.13        2020-04-13 [1] CRAN (R 4.0.0)                
#>  yaml          2.2.1       2020-02-01 [1] CRAN (R 4.0.0)                
#> 
#> [1] /Users/romainfrancois/.R/library/4.0
#> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

Do we still expect that we sill get implementations of `slice()` via `slice_()` ?

**Comment by hadley** [comment]
I don't know if there's much we can do about this without removing all the lazyeval fallbacks, which I don't think we can do until 1.1.0 (at the earliest).

**Comment by hadley** [comment]
BTW I think the real fix is to remove `slice.default()` - see #5083

**Pull request closed without merging**
