### PR TITLE
+ vignette that loads tibble, reproducing bug #3761

### PR DESCRIPTION
**Pull request by romainfrancois**
don't merge this

replaces #4024

bug discussed in #3761

### CODE REVIEW

**Comment by romainfrancois** [comment]
Getting this locally now. 

```
[bug-tibble-vignette2] 304.4 MiB ❯ devtools::build_vignettes()
Building dplyr vignettes
--- re-building ‘aaa.Rmd’ using rmarkdown
--- finished re-building ‘aaa.Rmd’

--- re-building ‘compatibility.Rmd’ using rmarkdown
--- finished re-building ‘compatibility.Rmd’

--- re-building ‘dplyr.Rmd’ using rmarkdown
`geom_smooth()` using method = 'gam' and formula 'y ~ s(x, bs = "cs")'
Warning: Removed 1 rows containing non-finite values (stat_smooth).
Warning: Removed 1 rows containing missing values (geom_point).
--- finished re-building ‘dplyr.Rmd’

--- re-building ‘programming.Rmd’ using rmarkdown
--- finished re-building ‘programming.Rmd’

--- re-building ‘two-table.Rmd’ using rmarkdown
Quitting from lines 39-45 (two-table.Rmd) 
Error: processing vignette 'two-table.Rmd' failed with diagnostics:
subscript out of bounds
--- failed re-building ‘two-table.Rmd’

--- re-building ‘window-functions.Rmd’ using rmarkdown
Quitting from lines 113-117 (window-functions.Rmd) 
Error: processing vignette 'window-functions.Rmd' failed with diagnostics:
subscript out of bounds
--- failed re-building ‘window-functions.Rmd’

SUMMARY: processing the following files failed:
  ‘two-table.Rmd’ ‘window-functions.Rmd’

Error : Vignette re-building failed.

Error: <callr_status_error in get_result(output = out, options):
 callr subprocess failed: Vignette re-building failed.>
-->
<simpleError: Vignette re-building failed.>

See `.Last.error.trace` for a stack trace.
[bug-tibble-vignette2] 312.7 MiB ❯ .Last.error.trace

 Stack trace:

 Process 50643:
 1. devtools::build_vignettes()
 2. callr::r(build, args = list(pkg_path = pkg$path, clean = clean,  ...
 3. callr:::get_result(output = out, options)

 x callr subprocess failed: Vignette re-building failed. 

 Process 51397:
 15. (function (pkg_path, clean, quiet, upgrade)  ...
 16. withr::with_temp_libpaths(action = "prefix", { ...
 17. base:::force(code)
 18. tools::buildVignettes(dir = pkg_path, clean = clean, tangle = TRUE,  ...
 19. base:::stop(msg, domain = NA, call. = FALSE)
 20. base:::.handleSimpleError(function (e)  ...
 21. h(simpleError(msg, call))

 x Vignette re-building failed. 
```

**Comment by hadley** [comment]
Doesn't reproduce with:

* knitting with `Cmd + Shift + K`
* `rmarkdown::render("vignettes/aaa.Rmd")`
* `callr::r(function() rmarkdown::render("vignettes/aaa.Rmd"))`

**Comment by hadley** [comment]
Wooo, got a minimal reprex:

``` r
library(tibble)
library(dplyr, warn.conflicts = FALSE)
knit_print.tbl_df <- function(x, options) {
  knitr::knit_print(trunc_mat(x), options)
}

knitr::knit_print(tibble::tibble(x = 1), list())
#> Error in FUN(X[[i]], ...): subscript out of bounds
```

<sup>Created on 2019-12-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Looks like that was added 5 years and after removing it I don't see any change in the appearance of the vignette.

**Pull request merged**
