### PR TITLE
Add use_tidy_github() files.

### PR DESCRIPTION
**Pull request by batpigandme**
* Add community files from `usethis::use_tidy_github()`.
* File under .github/.
* Add CODE_OF_CONDUCT.md.
* Add CONTRIBUTING.md.
* Add ISSUE_TEMPLATE.md.
* Add SUPPORT.md.

### CODE REVIEW

**Comment by batpigandme** [comment]
@jennybc This uses the latest github version of usethis, just want to double check that there's nothing in the works.

**Comment by batpigandme** [comment]
@krlmlr good call – removed the ones currently in the top-level directory. (cc @hadley, will this mess with pkgdown?)

**Comment by jennybc** [comment]
> @jennybc This uses the latest github version of usethis, just want to double check that there's nothing in the works

Hmm, hold on. I changed some wording around Code of Conduct in the snippet that goes in README but I see now that CONTRIBUTING.md also needs the same update. Let me do that in usethis and you'll need to re-apply `usethis::use_tidy_github()` and update this PR.

**Comment by batpigandme** [comment]
@jennybc copy that — just LMK when it's good to go!

**Comment by jennybc** [comment]
OK the tidyverse CONTRIBUTING template in usethis now frames the CoC in the same way as in README: it names the project/package and that it's about contributing to the project/package.

**Comment by batpigandme** [comment]
Thanks Jenny. It looks like there's no change to what's present in this repo.

**Comment by krlmlr** [comment]
Thanks! Does this close #3649?

**Comment by jennybc** [comment]
> It looks like there's no change to what's present in this repo.

Seems like this change to the usethis CONTRIBUTING template for a tidyverse package should show up here:
https://github.com/r-lib/usethis/commit/8483d1edbec15e36ba72bf1f4fb5ab5dad44acf7#diff-18e01a15bfba922856ec525378024dec

**Pull request merged**
