### PR TITLE
Refactoring, logging and tests for active bindings

### PR DESCRIPTION
**Pull request by krlmlr**
Follow-up to #3847

### CODE REVIEW

**Comment by krlmlr** [comment]
There's still something going on, but it may be related to _pkgload_ / _devtools_. Running the new test twice in the same R session reliably crashes. Same for this branch and for `master` with ad8b7bca cherry-picked. Can you replicate?

```sh
> R -q -e 'devtools::load_all(); dplyr:::init_logging("VERB"); devtools::test(f = "active-"); devtools::test(f = "active-")'
```

**Comment by romainfrancois** [comment]
I can run the test just fine, but I don't have logging enabled: 

```r
romain@purrplex ~/git/tidyverse/dplyr $ R -q -e 'devtools::load_all(); dplyr:::init_logging("VERB"); devtools::test(f = "active-"); devtools::test(f = "active-")'
> devtools::load_all(); dplyr:::init_logging("VERB"); devtools::test(f = "active-"); devtools::test(f = "active-")
Loading dplyr
Warning message:
In dplyr:::init_logging("VERB") :
  Logging not enabled, #define PLOGR_ENABLE when compiling the package
Loading dplyr
Testing dplyr
✔ |  OK F W S | Context
✔ |   1       | test-active-bindings [0.4 s]

══ Results ═════════════════════════════════════════════════════════════════════
Duration: 0.4 s

OK:       1
Failed:   0
Warnings: 0
Skipped:  0
Loading dplyr
Testing dplyr
✔ |  OK F W S | Context
✔ |   1       | test-active-bindings [0.4 s]

══ Results ═════════════════════════════════════════════════════════════════════
Duration: 0.4 s

OK:       1
Failed:   0
Warnings: 0
Skipped:  0
>
```

**Comment by krlmlr** [comment]
I still get the crash even when I don't start the logging and/or remove `-DPLOGR_ENABLE` . What version of _devtools_ are you running?

**Comment by romainfrancois** [comment]
```

**Comment by krlmlr** [comment]
Same with most recent _pkgload_. Working on a reprex, it's very weird.

**Comment by krlmlr** [comment]
Turns out that an out-of-date installation of _R6_ (and perhaps other packages) triggers the fault. I had some packages installed from source in R 3.5.0 (on Linux), reinstalling fixes the problem.

What a mess.

But this PR should be good then.

**Comment by krlmlr** [comment]
Yeah, fresh install + old _R6_ triggers the problem already. I don't even know where to file it.

**Pull request merged**
