### PR TITLE
Refresh distinct docs

### PR DESCRIPTION
**Pull request by rbjanis**
Addresses #4796

### CODE REVIEW

**Comment by romainfrancois** [comment]
Maybe something like this for `across()` example: 

- `distinct(across(starts_with("Sepal")))` gives you the same as `distinct(Sepal.Length, Sepal.Width)`
- `distinct(across(starts_with("Sepal"), round))` same as `distinct(Sepal.Length = round(Sepal.Length), Sepal.Width = round(Sepal.Width))`

Maybe using `mtcars` is better though

``` r
library(dplyr, warn.conflicts = FALSE)

iris %>% 
  group_by(Species) %>% 
  distinct(across(starts_with("Sepal")))
#> # A tibble: 127 x 3
#> # Groups:   Species [3]
#>    Sepal.Length Sepal.Width Species
#>           <dbl>       <dbl> <fct>  
#>  1          5.1         3.5 setosa 
#>  2          4.9         3   setosa 
#>  3          4.7         3.2 setosa 
#>  4          4.6         3.1 setosa 
#>  5          5           3.6 setosa 
#>  6          5.4         3.9 setosa 
#>  7          4.6         3.4 setosa 
#>  8          5           3.4 setosa 
#>  9          4.4         2.9 setosa 
#> 10          4.9         3.1 setosa 
#> # … with 117 more rows

iris %>% 
  group_by(Species) %>% 
  distinct(across(starts_with("Sepal"), round))
#> # A tibble: 18 x 3
#> # Groups:   Species [3]
#>    Sepal.Length Sepal.Width Species   
#>           <dbl>       <dbl> <fct>     
#>  1            5           4 setosa    
#>  2            5           3 setosa    
#>  3            4           3 setosa    
#>  4            6           4 setosa    
#>  5            4           2 setosa    
#>  6            7           3 versicolor
#>  7            6           3 versicolor
#>  8            6           2 versicolor
#>  9            5           2 versicolor
#> 10            5           3 versicolor
#> 11            6           3 virginica 
#> 12            7           3 virginica 
#> 13            8           3 virginica 
#> 14            5           2 virginica 
#> 15            7           2 virginica 
#> 16            7           4 virginica 
#> 17            6           2 virginica 
#> 18            8           4 virginica
```

<sup>Created on 2020-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by batpigandme** [comment]
@romainfrancois Do you want to push to this PR? I think the uses of `across()` stuff might be a good place for you to step in! 😄

**Comment by romainfrancois** [comment]
Sure. Feel free to ping me if you see other `across()` stuff 🤓

**Comment by romainfrancois** [comment]
Let's go `usethis::pr_fetch(4815)`

**Comment by romainfrancois** [comment]
* [x] Ensure there's one example that shows `across()`

**Comment by rbjanis** [comment]
If one of the goals was go get away from using `mtcars` and `iris` in examples, `across(contains("color"))` from the `starwars` data set would work.

``` r
library(tidyverse)

starwars %>% 
  distinct(across(contains("color")))
#> # A tibble: 67 x 3
#>    hair_color    skin_color  eye_color
#>    <chr>         <chr>       <chr>    
#>  1 blond         fair        blue     
#>  2 <NA>          gold        yellow   
#>  3 <NA>          white, blue red      
#>  4 none          white       yellow   
#>  5 brown         light       brown    
#>  6 brown, grey   light       blue     
#>  7 brown         light       blue     
#>  8 <NA>          white, red  red      
#>  9 black         light       brown    
#> 10 auburn, white fair        blue-gray
#> # … with 57 more rows
```

<sup>Created on 2020-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romainfrancois** [comment]
yes @rbjanis this is much better, I appear to be stuck in the `irisverse` for some reason. 

Do you want to replace my changes with this example ?

**Comment by rbjanis** [comment]
Yes, I can do that!

**Pull request merged**
