### PR TITLE
Get rid of rlang remote

### PR DESCRIPTION
**Pull request by krlmlr**
Tests seem to pass with CRAN rlang.

### CODE REVIEW

**Comment by lionel-** [comment]
Weird, 0.1.2 does not contain the fix implemented here https://github.com/tidyverse/rlang/commit/638db926bdee5b92e6330fc644a5957a59c46ca9

**Comment by krlmlr** [comment]
Where is this fix tested? Do I need to run on Windows to see the problem? What do we need to do to be compatible with rlang 0.1.2?

**Comment by lionel-** [comment]
This PR added the tests: https://github.com/tidyverse/dplyr/pull/2886

**Comment by krlmlr** [comment]
Yes, I'll probably disable these tests for now so that we don't need to wait for an rlang release. Need to fix AppVeyor tests, too.

**Pull request merged**
