### PR TITLE
Ensuring `i` refers to internal loop variable, not column name

### LINKED ISSUE #4380: select_if doesn't work if a column in the tibble is named "i"
This one took me a few minutes to track down... It appears that if a column in the tibble is named `i`, `select_if` will fail. This also applies to `mutate_if` and possibly others.

```r
packageVersion("dplyr")
[1] ‘0.8.1’

iris %>% 
rename(i=Sepal.Length) %>% 
select_if(is.numeric)

Error in tibble_vars[[i]] : 
  attempt to select more than one element in vectorIndex
```

### PR DESCRIPTION
**Pull request by romatik**
Closes #4380

### CODE REVIEW

**Comment by romatik** [comment]
`.p` works, all other variants break with `tibble_vars` breaking silently:
``` r
library(dplyr, warn.conflicts = FALSE)

packageVersion("dplyr")
#> [1] '0.8.1'

# works
.tbl <- iris %>% 
  rename(.p = Sepal.Length)
.predicate <- dplyr:::as_fun_list(is.numeric, caller_env())
dplyr:::tbl_if_vars(.tbl, .predicate, caller_env(), .include_group_vars = TRUE)
#> [1] ".p"           "Sepal.Width"  "Petal.Length" "Petal.Width"


# doesn't work
.tbl <- iris %>% 
  rename(i = Sepal.Length)
.predicate <- dplyr:::as_fun_list(is.numeric, caller_env())
dplyr:::tbl_if_vars(.tbl, .predicate, caller_env(), .include_group_vars = TRUE)
#> Error in tibble_vars[[i]]: attempt to select more than one element in vectorIndex


# doesn't work
.tbl <- iris %>% 
  rename(.tbl = Sepal.Length)
.predicate <- dplyr:::as_fun_list(is.numeric, caller_env())
dplyr:::tbl_if_vars(.tbl, .predicate, caller_env(), .include_group_vars = TRUE)
#> Error in .tbl[[tibble_vars[[i]]]]: subscript out of bounds


# doesn't work
.tbl <- iris %>% 
  rename(tibble_vars = Sepal.Length)
.predicate <- dplyr:::as_fun_list(is.numeric, caller_env())
dplyr:::tbl_if_vars(.tbl, .predicate, caller_env(), .include_group_vars = TRUE)
#> [1] "Sepal.Width"  "Petal.Length" "Petal.Width"
```

<sup>Created on 2019-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'll work on your suggestion to see how all of those cases can be solved.

**Comment by romatik** [comment]
Now it works for all 4 cases:
``` r
library(dplyr, warn.conflicts = FALSE)

iris <- tibble::as_tibble(iris)

packageVersion("dplyr")
#> [1] '0.8.1.9000'
iris %>% 
  rename(i=Sepal.Length) %>% 
  select_if(is.numeric)
#> # A tibble: 150 x 4
#>        i Sepal.Width Petal.Length Petal.Width
#>    <dbl>       <dbl>        <dbl>       <dbl>
#>  1   5.1         3.5          1.4         0.2
#>  2   4.9         3            1.4         0.2
#>  3   4.7         3.2          1.3         0.2
#>  4   4.6         3.1          1.5         0.2
#>  5   5           3.6          1.4         0.2
#>  6   5.4         3.9          1.7         0.4
#>  7   4.6         3.4          1.4         0.3
#>  8   5           3.4          1.5         0.2
#>  9   4.4         2.9          1.4         0.2
#> 10   4.9         3.1          1.5         0.1
#> # … with 140 more rows

# works
iris %>% 
  rename(p = Sepal.Length) %>% 
  select_if(is.numeric)
#> # A tibble: 150 x 4
#>        p Sepal.Width Petal.Length Petal.Width
#>    <dbl>       <dbl>        <dbl>       <dbl>
#>  1   5.1         3.5          1.4         0.2
#>  2   4.9         3            1.4         0.2
#>  3   4.7         3.2          1.3         0.2
#>  4   4.6         3.1          1.5         0.2
#>  5   5           3.6          1.4         0.2
#>  6   5.4         3.9          1.7         0.4
#>  7   4.6         3.4          1.4         0.3
#>  8   5           3.4          1.5         0.2
#>  9   4.4         2.9          1.4         0.2
#> 10   4.9         3.1          1.5         0.1
#> # … with 140 more rows

# works
iris %>% 
  rename(i = Sepal.Length) %>% 
  select_if(is.numeric)
#> # A tibble: 150 x 4
#>        i Sepal.Width Petal.Length Petal.Width
#>    <dbl>       <dbl>        <dbl>       <dbl>
#>  1   5.1         3.5          1.4         0.2
#>  2   4.9         3            1.4         0.2
#>  3   4.7         3.2          1.3         0.2
#>  4   4.6         3.1          1.5         0.2
#>  5   5           3.6          1.4         0.2
#>  6   5.4         3.9          1.7         0.4
#>  7   4.6         3.4          1.4         0.3
#>  8   5           3.4          1.5         0.2
#>  9   4.4         2.9          1.4         0.2
#> 10   4.9         3.1          1.5         0.1
#> # … with 140 more rows

# works
iris %>% 
  rename(.tbl = Sepal.Length) %>% 
  select_if(is.numeric)
#> # A tibble: 150 x 4
#>     .tbl Sepal.Width Petal.Length Petal.Width
#>    <dbl>       <dbl>        <dbl>       <dbl>
#>  1   5.1         3.5          1.4         0.2
#>  2   4.9         3            1.4         0.2
#>  3   4.7         3.2          1.3         0.2
#>  4   4.6         3.1          1.5         0.2
#>  5   5           3.6          1.4         0.2
#>  6   5.4         3.9          1.7         0.4
#>  7   4.6         3.4          1.4         0.3
#>  8   5           3.4          1.5         0.2
#>  9   4.4         2.9          1.4         0.2
#> 10   4.9         3.1          1.5         0.1
#> # … with 140 more rows

# works
iris %>% 
  rename(tibble_vars = Sepal.Length) %>% 
  select_if(is.numeric)
#> # A tibble: 150 x 4
#>    tibble_vars Sepal.Width Petal.Length Petal.Width
#>          <dbl>       <dbl>        <dbl>       <dbl>
#>  1         5.1         3.5          1.4         0.2
#>  2         4.9         3            1.4         0.2
#>  3         4.7         3.2          1.3         0.2
#>  4         4.6         3.1          1.5         0.2
#>  5         5           3.6          1.4         0.2
#>  6         5.4         3.9          1.7         0.4
#>  7         4.6         3.4          1.4         0.3
#>  8         5           3.4          1.5         0.2
#>  9         4.4         2.9          1.4         0.2
#> 10         4.9         3.1          1.5         0.1
#> # … with 140 more rows
```

<sup>Created on 2019-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by romatik** [comment]
@lionel- , is there a specific reason for `as_data_mask` in there? Current implementation works without it and no tests are failing, but perhaps I'm missing something obvious.

**Comment by krlmlr** [comment]
I think this is needed so that the `...` can refer to column names. But I'm confused by the documentation for `...` in `?select_if` :

> ...: Additional arguments for the function calls in .funs. These are evaluated only once, with tidy dots support.

Also, no tests seem to fail after getting rid of this change. The data mask was introduced only recently: 85060e50.

**Comment by lionel-** [comment]
>  is there a specific reason for as_data_mask here?

Creating a data mask is expensive so it is best done outside the loop. If we just call `eval_tidy()` with raw data the mask will be created at each iteration.

> I think this is needed so that the ... can refer to column names.

Since we don't capture `...` in quosures, these dots are not masked. I don't remember why we evaluate in a mask though. I'm not even sure why NSE is needed at all here. Perhaps try to remove the `eval_tidy()` and the `quo()`?

**Comment by romatik** [comment]
> I'm not even sure why NSE is needed at all here. Perhaps try to remove the eval_tidy() and the quo()?

That was my feeling as well. I'll remove it and report back

**Comment by romatik** [comment]
It looks like removing `eval_tidy` breaks something that I don't understand. 

If `for` loop looks like this:
```
  for (i in seq_len(n)) {
    column <- .tbl[[tibble_vars[[i]]]]
    selected[[i]] <- eval_tidy(.p(column, ...))
  }
```
then following tests run successfully (they are at line 33-34 at `test-colwise-select.R`:
``` r
library(dplyr, warn.conflicts = FALSE)
df <- tibble(x = 0L, y = 0.5, z = 1)
select_if(df, list(~rlang:::is_integerish(.)), list(~toupper(.)))
#> # A tibble: 1 x 2
#>       X     Z
#>   <int> <dbl>
#> 1     0     1
select_if(df, funs(rlang:::is_integerish(.)), funs(toupper(.)))
#> # A tibble: 1 x 2
#>       X     Z
#>   <int> <dbl>
#> 1     0     1
```

<sup>Created on 2019-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If I remove `eval_tidy` and make `for` loop like this:
```
  for (i in seq_len(n)) {
    column <- .tbl[[tibble_vars[[i]]]]
    selected[[i]] <- .p(column, ...)
  }
```

then 2 tests that use `list` instead of `funs` fail:
``` r
library(dplyr, warn.conflicts = FALSE)
df <- tibble(x = 0L, y = 0.5, z = 1)
select_if(df, list(~rlang:::is_integerish(.)), list(~toupper(.)))
#> Error in selected[[i]] <- .p(column, ...): long vectors not supported yet: subassign.c:1814
select_if(df, funs(rlang:::is_integerish(.)), funs(toupper(.)))
#> # A tibble: 1 x 2
#>       X     Z
#>   <int> <dbl>
#> 1     0     1
```

<sup>Created on 2019-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'm not sure why this error fire only with `list`, but not with `funs`, so not sure what is the better solution. 
@lionel- , would `eval_tidy` be expensive in this case?

**Comment by lionel-** [comment]
No worries, we can just keep using `eval_tidy()`.

**Comment by romainfrancois** [comment]
Thanks. 

btw @romatik it usually is a good idea to create a pull request from a *branch* in your fork, i.e. not *master*

**Pull request merged**
