### PR TITLE
WIP: Update programming vignette

### PR DESCRIPTION
**Pull request by lionel-**

### CODE REVIEW

**Comment by krlmlr** [comment]
@lionel- @jennybc: The *dplyr* 0.7.5 release is scheduled for March, can we include this in the upcoming release?

**Comment by jennybc** [comment]
This is listed in my project so I would read and review it.

@lionel- Is that a helpful thing for me to do? Happy to do so or to hold off or review something else.

**Comment by lionel-** [comment]
The first part about quasiquotation is finished I think, so a partial review would be helpful. However I'm not sure what are @hadley's plans for the vignette now that he has more experience and new insights about teaching tidy eval (e.g. code is a tree).

**Comment by romainfrancois** [comment]
@lionel- is this superseded by the tidyeval bookdown ?

**Comment by lionel-** [comment]
Yes we'll probably need to redirect people there.

**Pull request closed without merging**
