### PR TITLE
Patch release 0.8.5

### PR DESCRIPTION
**Pull request by lionel-**
Assigning the unbound value will likely become an error in the next R version.

### CODE REVIEW

**Comment by lionel-** [comment]
I'll run a bunch of revdepchecks overnight just to be sure.

**Comment by hadley** [comment]
Can you please also fix the stringsAsFactors test failures on r-devel for the patch release?

**Comment by lionel-** [comment]
Done in https://github.com/tidyverse/dplyr/pull/4928/commits/02c9c70fcc244795b08a94b13046238cdb401eae

**Comment by lionel-** [comment]
It was a good move to run full revdepchecks. There's a few instances of

```
libc++abi.dylib: terminating with uncaught exception of type Rcpp::no_such_binding: No such binding: n.
```

**Pull request merged**
