### PR TITLE
Add a `.method` argument to the data frame method of `arrange()`

### LINKED ISSUE #4962: Performance drop-off for `arrange()`
The dev version of dplyr has a performance drop-off when using `arrange()`.

``` r
library(dplyr, warn.conflicts = FALSE)
library(bench)

data_size <- 1000000
test_df <- tibble(a = sample(c("a","a","b","c","d"), data_size, TRUE),
                  b = sample(1:20, data_size, TRUE))

bench::mark(
  tidyverse = arrange(test_df, a, b),
  check = FALSE,
  iterations = 5)

# dplyr 0.8.5
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 tidyverse     369ms    372ms      2.69    19.2MB     4.04

# dplyr 1.0.0 dev
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 tidyverse     2.18s    2.24s     0.446    48.3MB    0.804
```

<sup>Created on 2020-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #4962

This PR adds a `.method` argument to the data frame method of `arrange()`. It defaults to `"dplyr_auto"`, but can also be any valid `order()` method.

`"dplyr_auto"` is more aggressive than `"auto"` in two ways:

- In addition to integer, numeric and logical vectors, it also uses radix ordering for character vectors. This forces the use of a C-locale, but is very fast. This is a breaking change for the defaults of `arrange()`.

- It uses `typeof()` rather than `is.*()` functions when determining if radix ordering can be used to operate at a level lower than S3 dispatch. This probably doesn't matter too much, because it is called on the comparison proxies of the columns (which generally returns the underlying raw data), but it still felt more correct.

```r
library(dplyr, warn.conflicts = FALSE)

set.seed(123)

size <- 1000000

df <- tibble(
  a = sample(c("a", "b", "c", "d"), size, replace = TRUE),
  b = sample(1:20, size, replace = TRUE)
)

# Master
bench::mark(arrange(df, a, b), iterations = 20)
#> # A tibble: 1 x 6
#>   expression             min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>        <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 arrange(df, a, b)    1.99s    2.22s     0.449    41.1MB     1.80

# This PR
bench::mark(arrange(df, a, b), iterations = 20)
#> # A tibble: 1 x 6
#>   expression             min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>        <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 arrange(df, a, b)   34.3ms   37.8ms      24.8    48.8MB     105.
```

### CODE REVIEW

**Comment by DavisVaughan** [comment]
Problems:

1) R 3.2 did not have a `method` argument at all, so it was forcibly chosen for you. Radix sorting still seems to have been done, but in a very small set of cases ("Method "radix" is only implemented for integer x with a range of less than 100,000")

2) R 3.3 does not have an `method = "auto"` option, and seems to default to `"shell"` unless explicitly specified as `"radix"`.

**Comment by romainfrancois** [comment]
Is the first problem enough justification to start depending on R > 3.3 ?

**Comment by DavisVaughan** [comment]
My current thoughts are that we will wait on this and maybe _eventually_ add a custom ordering function to vctrs that works on R 3.2 and uses radix sorting, along with the ability to specify ascending/descending per column, but I might be wrong. It seems like that will be a tough project though

**Comment by DavisVaughan** [comment]
Superseded by #6263

**Pull request closed without merging**
