### PR TITLE
ignore data frames with 0 columns as results in summarise()

### PR DESCRIPTION
**Pull request by romainfrancois**
``` r
library(dplyr, warn.conflicts = FALSE)
df <- tibble(g1 = factor(letters[1:10]), g2 = factor(letters[1:10]))

df %>%
  group_by(g1, g2) %>% 
  summarise(across(is.factor, nlevels))
#> # A tibble: 10 x 2
#> # Groups:   g1 [10]
#>    g1    g2   
#>    <fct> <fct>
#>  1 a     a    
#>  2 b     b    
#>  3 c     c    
#>  4 d     d    
#>  5 e     e    
#>  6 f     f    
#>  7 g     g    
#>  8 h     h    
#>  9 i     i    
#> 10 j     j
```

<sup>Created on 2020-04-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

initial example in #5084: 

``` r
library(dplyr, warn.conflicts = FALSE)

# Test DF
df <- tibble(g1 = factor(letters[1:10]),
  g2 = factor(LETTERS[1:10]),
  a  = runif(10, 1, 10),
  b  = runif(10, 10, 20),
  c  = runif(10, 15, 30),
  d  = runif(10, 1, 50))

df %>%
  group_by(g1, g2) %>% 
  summarise(
    across(is.numeric, mean), 
    across(is.factor, nlevels),
    n = n(), 
  )
#> # A tibble: 10 x 7
#> # Groups:   g1 [10]
#>    g1    g2        a     b     c     d     n
#>    <fct> <fct> <dbl> <dbl> <dbl> <dbl> <int>
#>  1 a     A      2.83  16.7  19.8  2.83     1
#>  2 b     B      8.76  19.3  18.3 46.0      1
#>  3 c     C      8.23  15.4  29.9 19.4      1
#>  4 d     D      9.92  14.8  23.4 10.8      1
#>  5 e     E      3.56  19.4  28.3  4.74     1
#>  6 f     F      8.87  10.8  16.1  8.05     1
#>  7 g     G      8.21  14.5  28.9 33.9      1
#>  8 h     H      5.78  19.7  19.1 41.2      1
#>  9 i     I      4.44  12.8  24.0 28.8      1
#> 10 j     J      5.94  13.4  25.8 11.3      1
```

<sup>Created on 2020-04-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by hadley** [comment]
Just wondering about this: would it be better to handle in `across()`? i.e. should it return `NULL` if there are no variables to iterate over?

**Comment by romainfrancois** [comment]
I think we could perhaps *also* do it, and then that would take advantage of `across()` caching, but just dealing with it in `across()` means other functions returning data frames might exhibit the same problems later.

**Comment by romainfrancois** [comment]
Also, `= NULL` is not legit in `summarise()`: 

``` r
library(dplyr, warn.conflicts = FALSE)

data.frame(x = 64) %>% 
  summarise(NULL)
#> Error: `summarise()` argument `..1` must be a vector.
#> ℹ `..1` is `NULL`.
#> x `..1` must be a vector, not NULL.
```

<sup>Created on 2020-04-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Yeah, I'm just trying to think what a 0-col data frame _should_ mean? Maybe `summarise()` should also ignore `NULL` columns? We do have a rough principle that `foo(x = NULL)` is often equivalent to `foo()` (although `mutate()` is an obvious exception).

But your solution seems simpler than thinking all this through.

**Comment by romainfrancois** [comment]
I just realize that we do infer the common type a few lines up, so I'll simplify the code some more when `result_type` is a 0 columns data frame.

**Pull request merged**
