### PR TITLE
Better checking of list arguments to bind_rows()

### LINKED ISSUE #3024: Bad error message when binding an unnamed list
```r
dplyr::bind_rows(list(1))
#> Error in bind_rows_(x, .id) : 'getCharCE' must be called on a CHARSXP
```

### PR DESCRIPTION
**Pull request by krlmlr**
Fixes #3024.

Related: https://github.com/billdenney/pknca/issues/48#issuecomment-326768053

### CODE REVIEW

**Comment by lionel-** [comment]
> Argument 1 must have names

I think it should be: Argument 1 must be named

**Comment by lionel-** [comment]
i.e. lists are treated as data frames so they should have outer names and the inner names of vectors are irrelevant.

**Comment by krlmlr** [comment]
To me, in `dplyr::bind_rows(a = df)`, the `df` is a named argument (because of the name `a`) but has names itself (the names of the columns. Can you please clarify which call should give which error message?

**Comment by lionel-** [comment]
If there are unused outer names it should probably be a warning.

**Comment by lionel-** [comment]
oh I understand now: "Argument 1 must have names". Argument 1 refers to the list, got it.

**Comment by lionel-** [comment]
> If there are unused outer names it should probably be a warning.

Though the outer names can be used as `.id` column right? So we should allow unused outer names.

**Comment by krlmlr** [comment]
I'm not sure, this PR is just about fixing an annoyance just before the upcoming dplyr bugfix release, which may or may not be connected with a segfault only CRAN is seeing. Can we discuss wording of error messages after the release?

**Comment by krlmlr** [comment]
Simplified the check.

**Pull request merged**
