### PR TITLE
Fix UTF-8 column name test for Windows

### PR DESCRIPTION
**Pull request by krlmlr**
and fix `rename()` with a hack.

### CODE REVIEW

**Comment by lionel-** [comment]
> Perhaps exprs() and quo() should unescape names?

I don't think so. Why doesn't `rename_vars()` work with UTF-8 names? Is it an issue in `setdiff()`?

**Comment by krlmlr** [comment]
No, foreign characters are mangled already by `exprs()`: https://github.com/tidyverse/dplyr/pull/2886/commits/1db519ce9bbcb6c1042bc1479c63ba07dc5e0d96#diff-736b31bba1292201e8910669af931883R188

**Comment by lionel-** [comment]
I see this in a latin1 R session, which looks right:

```r
library("rlang")
x <- exprs("\u5e78" := 10)

names(x)
#> [1] "å¹¸"

Encoding(names(x))
#> [1] "UTF-8"
```

**Comment by lionel-** [comment]
oops sorry, the shell was in latin1 but not the R session. This is actually:

```r
mut_latin1_locale()
x <- exprs("\u5e78" := 10)

Encoding(names(x))
#> [1] "UTF-8"

names(x)
#> "<U+5E78>"
```

**Comment by krlmlr** [comment]
This is on Windows:

``` r
library(rlang)
x <- exprs("\u5e78" := 10)
charToRaw(names(x))
#> [1] e5 b9 b8
Encoding(names(x))
#> [1] "UTF-8"
```

This looks right, but the last commit seems to resolve the problems with `rename()`. Will investigate.

**Comment by krlmlr** [comment]
This is after reverting 1db519c:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
data_frame(a = 1) %>% rename("\u5e78" := a) %>% names %>% charToRaw
#> [1] 3c 55 2b 35 45 37 38 3e
```

**Comment by lionel-** [comment]
yes, just saw that the bytes are right and it's the print method that escapes unicode. I wish they gave more clues about what's going on in that method.

**Comment by krlmlr** [comment]
Still, my last commit may be curing the wrong problem. I'll be looking into it.

**Comment by krlmlr** [comment]
Could it be that uqs in dataframe.R:123 mangles foreign characters?

**Comment by krlmlr** [comment]
It appears so:

``` r
library(rlang)
f <- function(...) {
  exprs <- exprs(...)
  charToRaw(names2(exprs))
}

g <- function(...) {
  f(!!! quos(...) )
}
g("\u5e78" := 10)
#> [1] 3c 55 2b 35 45 37 38 3e
```

**Comment by lionel-** [comment]
good catch, looks like it:

```r
exprs <- exprs("\u5e78" := 10)
x <- quos(!!! exprs)

chr_encoding(names(x))
#> [1] "unknown"

as_bytes(names(x))
#> [1] 3c 55 2b 35 45 37 38 3e
```

**Comment by krlmlr** [comment]
Back to my original question: Maybe demangle right in `exprs()` and `quos()`?

**Comment by lionel-** [comment]
I think this needs to be done here: https://github.com/tidyverse/rlang/blob/d92dbde3886f65c7e197776174f095ba621739d8/R/dots.R#L191

**Comment by krlmlr** [comment]
I don't know rlang well enough to comment on this, but we should be able to write tests that indicate if this works as expected. Perhaps we should also turn on testing on AppVeyor?

**Comment by lionel-** [comment]
I think it's just a matter of running `mut_latin1_locale()` before running the test. It should work even if R is launched in a shell run with a UTF-8 locale. I'll look into it.

**Comment by krlmlr** [comment]
I remember adding `with_` functions to dplyr test helpers for this purpose.

It's great to emulate an OS without UTF-8 support, but testing on that OS may reveal other problems.

**Pull request merged**
