### PR TITLE
turn off hybrid inside inline function declarations

### PR DESCRIPTION
**Pull request by romainfrancois**

### CODE REVIEW

**Comment by romainfrancois** [comment]
not finished. but `n4` is fine in that case: 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(purrr)

df <- tibble(x = list(
  tibble(y = 1:2),
  tibble(y = 1:3),
  tibble(y = 1:4)
))

nrows <- function(df) {
  df %>% summarise(n = n()) %>% .[["n"]]
}

nrows_magrittr_lambda <- . %>% summarise(n = n()) %>% .[["n"]]

mutate( df,
  n1 = x %>% map_int(nrows),
  n5 = map_int(x, nrows_magrittr_lambda),

  # n2 = x %>% map_int(. %>% summarise(n = n()) %>% .[["n"]]),
  # n3 = map_int(x, ~ summarise(., n = n())[["n"]]),
  n4 = map_int(x, function(df) summarise(df, n = n())[["n"]])
)
#> # A tibble: 3 x 4
#>   x                   n1    n5    n4
#>   <list>           <int> <int> <int>
#> 1 <tibble [2 × 1]>     2     2     2
#> 2 <tibble [3 × 1]>     3     3     3
#> 3 <tibble [4 × 1]>     4     4     4
```

Created on 2018-03-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by romainfrancois** [comment]
Not sure how to deal with the other cases. 

Problem is the inner function should be doing the hybrid evaluation, but the outer does in too early. 

```
mutate( df,
  n2 = x %>% map_int(. %>% summarise(n = n()) %>% .[["n"]])
)
```

Perhaps when we see dplyr functions, we should not try to simplify the call, but this is probably not general enough.

**Comment by krlmlr** [comment]
To me, it looks like we need our own implementation of `Rf_eval()` to fully solve this.

**Comment by krlmlr** [comment]
Is this still necessary with #3526?

**Comment by romainfrancois** [comment]
probably not. The hope is that #3526 will eliminate that class of problems. This was half baked anyway.

**Pull request closed without merging**
