### PR TITLE
WIP: vignette that loads tibble, reproducing bug #3761

### PR DESCRIPTION
**Pull request by romainfrancois**
(don't merge this)

### CODE REVIEW

**Comment by krlmlr** [comment]
With the dev version of _tibble_ the error looks slightly different: https://travis-ci.org/tidyverse/dplyr/jobs/471192729#L1103.

The way I understand the error, adding a vignette that loads _tibble_ triggers an error in **another** vignette. Maybe some code in `.onLoad()` isn't handling this situation well, perhaps the S3 registration? @lionel-: Any idea?

**Comment by romainfrancois** [comment]
This thing makes me anxious 😰

**Comment by hadley** [comment]
Don't you also need a `sink()`? (https://adv-r.hadley.nz/debugging.html#rmarkdown)

**Comment by romainfrancois** [comment]
replaced by #4665

**Pull request closed without merging**
