### PR TITLE
ntile() uses database logic: larger bins come first

### LINKED ISSUE #4995: ntile() distributes remainders across buckets differently in dplyr vs database
Hi!  👋   I'm seeing slight differences in the way `ntile()` distributes "remainders" across buckets in dplyr versus in the database I'm using (Redshift). 

For example, when we divide mtcars (32 rows) into 5 buckets, the two remainders are distributed into bucket 1 & 3 (arrows mine).

``` r
library(dplyr)

mtcars_dplyr <- mtcars %>% 
  mutate(bucket = ntile(mpg, 5)) %>% 
  select(mpg, bucket)

mtcars_dplyr %>% count(bucket)
#> # A tibble: 5 x 2
#>   bucket     n
#>    <int> <int>
#> 1      1     7 <-----
#> 2      2     6
#> 3      3     7 <-----
#> 4      4     6
#> 5      5     6
```

<sup>Created on 2020-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

When I do the same in the database, the remainders get distributed to the buckets in order. The [Oracle docs](https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions101.htm) describe it this way:

> The remainder values (the remainder of number of rows divided by buckets) are distributed one for each bucket, starting with bucket 1. 

``` r
library(dplyr)
library(dbplyr)

mtcars_db <- tbl_memdb(mtcars)

mtcars_db <- mtcars_db %>%
  mutate(bucket = ntile(mpg, 5)) %>%
  select(mpg, bucket) %>%
  collect()

mtcars_db %>% count(bucket)
#> # A tibble: 5 x 2
#>   bucket     n
#>    <int> <int>
#> 1      1     7 <-----
#> 2      2     7 <-----
#> 3      3     6
#> 4      4     6
#> 5      5     6
```

<sup>Created on 2020-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

_Update:_ I updated RSQLite and was able to generate a reprex of the db part to.

Let me know if there's anything else I can do on my end!

### PR DESCRIPTION
**Pull request by krlmlr**
I remember this was hard to solve arithmetically; `.bincode()` should work reasonably fast for `n` not too large.

Closes #4995.

### CODE REVIEW

**Comment by krlmlr** [comment]
We could do better with an `if_else()`.

**Comment by hadley** [comment]
Can you please merge/rebase just to make the check errors go away?

**Comment by krlmlr** [comment]
Done, switched to `if_else()` which I think is better than `.bincode()` even in the current version.

**Comment by krlmlr** [comment]
Current test errors are unrelated.

**Comment by krlmlr** [comment]
Should we check for invalid `n` ?

Timings are a bit worse but don't look too bad, we're doing more (useless) work now. Do we want to improve?

## This PR

``` r
library(dplyr)
set.seed(20200327)
N <- 1e6
x <- runif(N)
bench::mark(
  ntile(N, floor(sqrt(N) + 1))
)
#> # A tibble: 1 x 6
#>   expression                        min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 ntile(N, floor(sqrt(N) + 1))   44.9µs   48.9µs    16375.     187KB     23.0
```

<sup>Created on 2020-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## c7f2936

``` r
library(dplyr)
set.seed(20200327)
N <- 1e6
x <- runif(N)
bench::mark(
  ntile(N, floor(sqrt(N) + 1))
)
#> # A tibble: 1 x 6
#>   expression                        min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 ntile(N, floor(sqrt(N) + 1))   30.1µs   33.1µs    24322.    54.6KB     21.9
```

<sup>Created on 2020-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
Updated benchmarks. With an optimized version of `if_else()` we can get down to 140 ms.

**Comment by hadley** [comment]
I don't think there's much point optimising this function any further as at some point we'll rewrite in C.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
