### PR TITLE
first_n() and last_n()

### PR DESCRIPTION
**Pull request by romainfrancois**
Follow up to #3911, need to merge #3911 first. 

To get the first or last `n` rows of each group: 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

iris %>% 
  group_by(Species) %>% 
  first_n(2)
#> # A tibble: 6 x 5
#> # Groups:   Species [3]
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species   
#>          <dbl>       <dbl>        <dbl>       <dbl> <fct>     
#> 1          5.1         3.5          1.4         0.2 setosa    
#> 2          4.9         3            1.4         0.2 setosa    
#> 3          7           3.2          4.7         1.4 versicolor
#> 4          6.4         3.2          4.5         1.5 versicolor
#> 5          6.3         3.3          6           2.5 virginica 
#> 6          5.8         2.7          5.1         1.9 virginica

iris %>% 
  group_by(Species) %>% 
  last_n(2)
#> # A tibble: 6 x 5
#> # Groups:   Species [3]
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species   
#>          <dbl>       <dbl>        <dbl>       <dbl> <fct>     
#> 1          5.3         3.7          1.5         0.2 setosa    
#> 2          5           3.3          1.4         0.2 setosa    
#> 3          5.1         2.5          3           1.1 versicolor
#> 4          5.7         2.8          4.1         1.3 versicolor
#> 5          6.2         3.4          5.4         2.3 virginica 
#> 6          5.9         3            5.1         1.8 virginica
```

Created on 2018-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)

### CODE REVIEW

**Comment by romainfrancois** [comment]
In particular, this deals with #3788: 

``` r
library(dplyr, warn.conflicts = FALSE)

f1 <- function(x, n, grouping_col) {
  x %>%
    group_by(!!enquo(grouping_col)) %>%
    filter(row_number() <= n) %>%
    ungroup()
}

# suggested by Inaki Ucar
f2 <- function(x, n, grouping_col) {
  x %>%
    group_by(!!enquo(grouping_col)) %>%
    mutate(gr_nr = row_number()) %>%
    ungroup() %>%
    filter(gr_nr <= n) %>%
    select(-gr_nr)
}

f4 <- function(x, n, grouping_col) {
  x %>%
    group_by(!!enquo(grouping_col)) %>%
    first_n(n)
}


x <- tibble(val = 1:10^4, group = rep(1:10^3, 10))
bench::mark(
  f1(x, 1, group),
  f2(x, 1, group),
  f4(x, 1, group)
)
#> # A tibble: 3 x 10
#>   expression     min    mean  median     max `itr/sec` mem_alloc  n_gc
#>   <chr>      <bch:t> <bch:t> <bch:t> <bch:t>     <dbl> <bch:byt> <dbl>
#> 1 f1(x, 1, … 14.66ms 15.63ms 15.47ms 18.35ms      64.0  841.99KB    13
#> 2 f2(x, 1, …  4.61ms  5.14ms  4.93ms 10.18ms     195.     2.07MB     5
#> 3 f4(x, 1, …  1.73ms  1.98ms  1.93ms  5.54ms     504.    50.77KB     6
#> # ... with 2 more variables: n_itr <int>, total_time <bch:tm>
```

Created on 2018-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)

**Comment by romainfrancois** [comment]
Alternatively this could be some hybrid handling of `:` in slice.

**Comment by romainfrancois** [comment]
@hadley is it worth having those special cases ?

**Comment by hadley** [comment]
Why would you use this over `slice()`?

**Comment by romainfrancois** [comment]
It's just faster, as it never has to evaluate any R expression.

**Comment by hadley** [comment]
In that case, it doesn't feel that compelling to me.

**Comment by romainfrancois** [comment]
Fair enough, perhaps at some point we'll have `slice` and `filter` hybrid evaluation so that these would be optimized: 

```
slice(1:n)
filter(row_number() <= n)
```

**Pull request closed without merging**
