### PR TITLE
Opt-in to new snapshot display

### PR DESCRIPTION
**Pull request by hadley**
@romainfrancois @lionel- this looks ok to me. Does it look ok to you? If so, I feel happy releasing testthat.

### CODE REVIEW

**Review by romainfrancois — APPROVED** [review]
Does this replace #6104 ?

**Comment by romainfrancois** [comment]
This probably needs to remote `testthat` for the time being.

**Review by lionel- — APPROVED** [review]
Looks good!

Just missing a Remotes on dev testthat.

**Comment by hadley** [comment]
Ooops, I somehow missed  #6104, sorry!

**Pull request closed without merging**
