### PR TITLE
`arrange()` fails on named arguments, e.g. when .by_group is used on …

### LINKED ISSUE #3546: arrange .by_group Argument Should Be Dropped for non-grouped_df Classes (or give a clearer error)
When accidentally trying to arrange a regular data.frame with `arrange`, I got a difficult to interpret error:

"Error in arrange_impl(.data, dots): incorrect size (1) at position 2, expecting : 2"

The issue was that I wasn't using a `grouped_df`; it was just a regular `data.frame`, and the `.by_group` argument only has meaning with the `grouped_df` class.

Theoretically, someone could have a column named `.by_group`, so I understand not having a general catch for that as an argument that is usually ignored.  When the quosure is named `.by_group`, it is a logical value of length 1, and it is not the same length as everything else, it would be helpful at the `arrange_impl` (or somewhere higher in the stack) gave a more useful error message indicating that the user probably didn't mean to use the argument (or maybe a warning and then ignore the argument).

``` r
library(dplyr)                                                              
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
                                                                            
# When not grouped, the ".by_group" argument is interpreted as a column when
# it reaches arrange_impl                                                   
data.frame(foo=1:2, bar=2) %>%                                              
arrange(foo, .by_group=TRUE)                                                
#> Error in arrange_impl(.data, dots): incorrect size (1) at position 2, expecting : 2
                                                                            
data.frame(foo=1:2, bar=2) %>%                                              
group_by(bar) %>%                                                           
arrange(foo, .by_group=TRUE)                                                
#> # A tibble: 2 x 2
#> # Groups:   bar [1]
#>     foo   bar
#>   <int> <dbl>
#> 1     1    2.
#> 2     2    2.
```

### PR DESCRIPTION
**Pull request by romainfrancois**
…a non grouped tibble. closes #3546

Make scoped arrange functions generic so that only the grouped_df case handles the .by_group argument

### CODE REVIEW

**Comment by hadley** [comment]
Do any of the other scoped verbs have generic versions?

**Comment by krlmlr** [comment]
Why not just add a `.by_group` argument to `arrange.data.frame()` ?

**Comment by krlmlr** [comment]
That's what this PR does (in a different way), do we still the scoped verbs to be S3 generics?

**Comment by hadley** [comment]
I don't think we want the scoped verbs to be generic. If we can solve this problem by adding an argument to `arrange.data.frame()` I think we should do so.

**Comment by romainfrancois** [comment]
Replaced by #3661

**Pull request closed without merging**
