### PR TITLE
Centralize static Rf_install calls.

### PR DESCRIPTION
**Pull request by romainfrancois**
So that symbols that are statically used, e.g. `Rf_install("n")` are initialized only once, and we get top them by `symbols().n`

I tried to rather have the syntax `symbols::n` but could not get it to work.

### CODE REVIEW

**Comment by krlmlr** [comment]
Not sure what you tried, but for `symbols::n` you need to

- declare `extern symbols_t symbols;` in the header
- define `symbols_t symbols;` in exactly one `.c` or `.cpp` file, in the appropriate `namespace`

https://stackoverflow.com/q/10422034/946850

**Comment by romainfrancois** [comment]
I'm fine with the `symbols().n` notation.

**Comment by romainfrancois** [comment]
Updated so now `symbols.h` has: 

```cpp
struct symbols {
  static SEXP package;
  static SEXP n;
  static SEXP tzone;
  ...
}
```

and those are defined in `init.cpp` : 

```cpp
namespace dplyr {

SEXP symbols::package = Rf_install("package");
SEXP symbols::n = Rf_install("n");
SEXP symbols::tzone = Rf_install("tzone");
SEXP symbols::units = Rf_install("units");
...
```

**Comment by romainfrancois** [comment]
That works for me, @krlmlr can you have a look please.

**Pull request merged**
