### PR TITLE
Fixes for `across()` substitution

### PR DESCRIPTION
**Pull request by romainfrancois**
identified as part of rev dep checks for release 1.0.7 #5894 

original problem: 

``` r
library(dplyr, warn.conflicts = FALSE)

local({
  limit <- 7
  df <- data.frame(x = 1:10, y = 10:1)
  
  filter(df, if_any(everything(), ~ .x > limit))
})
#> Error: Problem with `filter()` input `..1`.
#> ℹ Input `..1` is `x > limit | y > limit`.
#> x object 'limit' not found
```

this breaks package `readabs`. 

```
> revdepcheck::cloud_details(, "readabs")
══ Reverse dependency check ═══════════════════════════════════════════════════════════════════════════════════ readabs 0.4.9 ══

Status: BROKEN

── Newly failing

x checking examples ... ERROR
x checking tests ... ERROR

── Before ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
0 errors ✓ | 0 warnings ✓ | 0 notes ✓

── After ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> checking examples ... ERROR
  Running examples in ‘readabs-Ex.R’ failed
  The error most likely occurred in:
  
  > ### Name: search_catalogues
  > ### Title: Search for ABS catalogues that match a string
  > ### Aliases: search_catalogues
  > 
  > ### ** Examples
  > 
  > 
  > search_catalogues("labour")
  Error: Problem with `filter()` input `..1`.
  ℹ Input `..1` is `|...`.
  ✖ object 'string' not found
  Backtrace:
       █
    1. ├─readabs::search_catalogues("labour")
    2. │ └─`%>%`(...)
    3. ├─dplyr::filter(...)
    4. ├─dplyr:::filter.data.frame(...)
    5. │ └─dplyr:::filter_rows(.data, ...)
    6. │   ├─base::withCallingHandlers(...)
    7. │   └─mask$eval_all_filter(dots, env_filter)
    8. ├─rlang:::grepl(string, heading, perl = TRUE, ignore.case = TRUE)
    9. ├─base::grepl(string, heading, perl = TRUE, ignore.case = TRUE)
   10. └─base::.handleSimpleError(...)
   11.   └─dplyr:::h(simpleError(msg, call))
  Execution halted

> checking tests ... ERROR
  See below...

── Test failures ───────────────────────────────────────────────────────────────────────────────────────────────── testthat ────

> library(testthat)
> library(readabs)
Environment variable 'R_READABS_PATH' is unset. Downloaded files will be saved in a temporary directory.
You can set 'R_READABS_PATH' at any time. To set it for the rest of this session, use
	Sys.setenv(R_READABS_PATH = <path>)
> 
> test_check("readabs")
══ Skipped tests ═══════════════════════════════════════════════════════════════
• On CRAN (26)

══ Failed tests ════════════════════════════════════════════════════════════════
── Error (test-search_catalogues.R:4:3): search_catalogues() returns appropriate output ──
Error: Problem with `filter()` input `..1`.
ℹ Input `..1` is `|...`.
✖ object 'string' not found
Backtrace:
     █
  1. ├─readabs::search_catalogues("labour") test-search_catalogues.R:4:2
  2. │ └─`%>%`(...)
  3. ├─dplyr::filter(...)
  4. ├─dplyr:::filter.data.frame(...)
  5. │ └─dplyr:::filter_rows(.data, ...)
  6. │   ├─base::withCallingHandlers(...)
  7. │   └─mask$eval_all_filter(dots, env_filter)
  8. ├─rlang:::grepl(string, heading, perl = TRUE, ignore.case = TRUE)
  9. ├─base::grepl(string, heading, perl = TRUE, ignore.case = TRUE)
 10. └─base::.handleSimpleError(...)
 11.   └─dplyr:::h(simpleError(msg, call))

[ FAIL 1 | WARN 0 | SKIP 26 | PASS 52 ]
Error: Test failures
Execution halted

2 errors x | 0 warnings ✓ | 0 notes ✓
```

### CODE REVIEW

**Comment by romainfrancois** [comment]
The `readabs` package tests pass with this pull request.

**Comment by romainfrancois** [comment]
``` r
library(dplyr, warn.conflicts = FALSE)

local({
  limit <- 7
  df <- data.frame(x = 1:10, y = 10:1)
  
  # this: 
  filter(df, if_any(everything(), ~ .x > limit))
  
  # should behave as if we typed this:
  # in particular in terms of the quosure environment
  filter(df, x > limit | y > limit)
})
#>    x  y
#> 1  1 10
#> 2  2  9
#> 3  3  8
#> 4  8  3
#> 5  9  2
#> 6 10  1
```

<sup>Created on 2021-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by romainfrancois** [comment]
This shouldn't be necessary: 

``` r
library(rlang)

q1 <- local({
  limit <- 7
  quo(x > limit)
})
q2 <- local({
  limit <- 7
  quo(y > limit)
})
expr <- call("|", q1, q2)
q <- as_quosure(expr, baseenv())
eval_tidy(q, new_data_mask(env(x = 1:10, y = 10:1)))
#>  [1]  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE
```

<sup>Created on 2021-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by romainfrancois** [comment]
Trying a different approach, as indeed the made up quosure can use `baseenv()` as its environment, since it embarks qu'usures: 

```r
Browse[2]> call(op, x, y)
(~x > limit) | ~y > limit
```

So then the problem was the environment of each of the individual quosures, these have to be able to find `limit`. 

With this change, we make a difference between a formula that wasn't evaluated yet, which can be evaluated in the quosure's environment: 

``` r
library(dplyr, warn.conflicts = FALSE)

local({
  limit <- 7
  df <- data.frame(x = 1:10, y = 10:1)
  
  filter(df, if_any(everything(), ~ .x > limit))
})
#>    x  y
#> 1  1 10
#> 2  2  9
#> 3  3  8
#> 4  8  3
#> 5  9  2
#> 6 10  1

local({
  df <- data.frame(x = 1:10, y = 10:1)
  
  filter(df, if_any(everything(), ~ {limit <- 7; .x > limit}))
})
#>    x  y
#> 1  1 10
#> 2  2  9
#> 3  3  8
#> 4  8  3
#> 5  9  2
#> 6 10  1
```

<sup>Created on 2021-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

and a formula that was previously evaluated: so the environment of the made quosure can just be the formula's environment : 

``` r
library(dplyr, warn.conflicts = FALSE)

f <- local({
  limit <- 7
  ~ .x > limit
})
df <- data.frame(x = 1:10, y = 10:1)
filter(df, if_any(everything(), f))
#>    x  y
#> 1  1 10
#> 2  2  9
#> 3  3  8
#> 4  8  3
#> 5  9  2
#> 6 10  1
```

<sup>Created on 2021-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

This requires that we are able to distinguish between evaluated formulas and non-evaluated formulas, and that's currently not possible when several functions are given, so this will be a problem when using lists, e.g. 

``` r
library(dplyr, warn.conflicts = FALSE)

local({
  limit <- 7
  df <- data.frame(x = 1:10, y = 10:1)
  
  filter(df, if_any(everything(), list(~ .x > limit)))
})
#> Error: Problem with `filter()` input `..1`.
#> ℹ Input `..1` is `x > limit | y > limit`.
#> x object 'limit' not found
```

<sup>Created on 2021-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by romainfrancois** [comment]
🤔 or maybe instead we can check the ancestry of `f_env(fn)` and discriminate based on "was the formula evaluated in env" ? @lionel-

**Comment by romainfrancois** [comment]
``` r
library(dplyr, warn.conflicts = FALSE)

local({
  limit <- 7
  df <- data.frame(x = 1:10, y = 10:1)
  
  filter(df, if_any(everything(), ~ .x > limit))
})
#>    x  y
#> 1  1 10
#> 2  2  9
#> 3  3  8
#> 4  8  3
#> 5  9  2
#> 6 10  1

local({
  df <- data.frame(x = 1:10, y = 10:1)
  
  filter(df, if_any(everything(), ~ {limit <- 7; .x > limit}))
})
#>    x  y
#> 1  1 10
#> 2  2  9
#> 3  3  8
#> 4  8  3
#> 5  9  2
#> 6 10  1

f <- local({
  limit <- 7
  ~ .x > limit
})
df <- data.frame(x = 1:10, y = 10:1)
filter(df, if_any(everything(), f))
#>    x  y
#> 1  1 10
#> 2  2  9
#> 3  3  8
#> 4  8  3
#> 5  9  2
#> 6 10  1

local({
  limit <- 7
  df <- data.frame(x = 1:10, y = 10:1)
  
  filter(df, if_any(everything(), list(~ .x > limit)))
})
#>    x  y
#> 1  1 10
#> 2  2  9
#> 3  3  8
#> 4  8  3
#> 5  9  2
#> 6 10  1
```

<sup>Created on 2021-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Review by lionel- — APPROVED** [review]
Looks good!

I like the detection of unevaluated formulas. Comparing the environment to the mask is also how we'll be able to inline `\(x)` or `function` lambdas.

Summary of our Slack discussion for reference: Stopping the substitution at `~` and `function` calls is similar to r-lib/rlang#845. The substitution approach is still not 100% correct compared to an evaluation approach but we hope that with this change it's reasonably correct for practical cases. The advantage of substitution is that it makes it easier to optimise across calls or transport it across backends by reusing the expansions.

**Pull request merged**
