### PR TITLE
Move responsibility to compute dots and by to method

### PR DESCRIPTION
**Pull request by krlmlr**
Required for #6526.

Also fixes default argument of internal helper.

### CODE REVIEW

**Comment by DavisVaughan** [comment]
@krlmlr do you still need this one? Right now `filter_rows()` and `slice_rows()` are rather symmetrical, which I like, so I'd rather only do this if we have to. 

We can definitely fix the bad default arg either way, of course

**Comment by krlmlr** [comment]
Good catch, `slice_rows()` has the same problem, fixed that 🤪 

I've added comments to the code to explain the reasoning for the separation.

**Comment by DavisVaughan** [comment]
@krlmlr would you please take a look at the CI?

**Comment by DavisVaughan** [comment]
Actually I see the problem, I'll take over and manage merging, thanks!

**Comment by krlmlr** [comment]
Thanks for taking over, I pushed too hastily.

**Pull request merged**
