### PR TITLE
Fix/group by empty

### LINKED ISSUE #3987: revert group_by(<empty>) creating a grouped Tibbles

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #3987

### CODE REVIEW

**Comment by hadley** [comment]
And revert the change to `count()`? And maybe document the return value in `group_by()`?

**Comment by romainfrancois** [comment]
Is this the problem ?

```r
> mtcars %>% group_by(cyl) %>% count()
# A tibble: 3 x 2
# Groups:   cyl [3]
    cyl     n
  <dbl> <int>
1     4    11
2     6     7
3     8    14
> mtcars  %>% count(cyl)
# A tibble: 3 x 2
    cyl     n
  <dbl> <int>
1     4    11
2     6     7
3     8    14
```

I'm struggling a bit about the history of `count()` and what it should do in all cases.

**Comment by hadley** [comment]
`count()` is supposed to maintain the grouping levels — I don't think the behaviour should change, but didn't you make a change to its code that can now be backed out?

**Comment by romainfrancois** [comment]
If I did, it was in #3964. I'll track it down.

**Comment by hadley** [comment]
Yeah, https://github.com/tidyverse/dplyr/pull/3964/files#diff-11056338056536e72a662cced1916964R176

**Pull request merged**
