### PR TITLE
Defunct underscore and _each() functions

### PR DESCRIPTION
**Pull request by romainfrancois**
In 1.0.3 we removed the `.default()` methods that were calling the underscore functions (the code says they were deprecated in 0.7.0). 

This makes them defunct. 

#5573

### CODE REVIEW

**Comment by hadley** [comment]
Technically this is removing them, which is another stage past defunct. I'm not sure if that's going to be too big a change or not — can you please run the revdeps to see if anything breaks?

**Comment by romainfrancois** [comment]
This, but rebased on `v1.0.5` breaks quite a bunch of packages: 

 - AQuadtree: summarise_()
 - arealDB: group_by(.dots=)
 - auctestr: filter_()
 - autoMrP: group_by(.dots=)
 - AzureKusto: group_by(.dots=)
 - banter: group_by(.dots=)
 - benthos: filter_()
 - bioinactivation: mutate_()
 - bioOED: mutate_()
 - bootnet: arrange_()
 - capm: select_()
 - carpenter: summarise_()
 - codified: select_()
 - cofeatureR: mutate_()
 - CollapseLevels: group_by_()
 - corporaexplorer: group_by(.dots=)
 - countyfloods: filter_()
 - countytimezones: select_()
 - cpr: mutate_()
 - crplyr: summarise_()
 - crsra: select_()
 - dat: mutate_()
 - DataCombine: group_by_()
 - dataCompareR: select_()
 - ddpcr: select_()
 - dmutate: distinct_()
 - eesim: mutate_()
 - emuR: arrange_()
 - eoffice: filter_()
 - EpiNow2: compilation issue, unrelated I guess
 - EpiSignalDetection: group_by_()
 - extdplyr: mutate_()
 - ezec: do_() 
 - factorMerger: arrange_()
 - fastqcr: select_()
 - funModeling: summarise_()
 - futureheatwaves: mutate_() select_()
 - GADMTools: select_()
 - gender: group_by(.dots=)
 - genogeographer: select_()
 - geogenr:  group_by(.dots=)
 - geomultistar: group_by(.dots=)
 - GFE: group_by_()
 - ggalluvial: group_by(.dots=)
 - ggedit: summarise_()
 - ggfocus: select_()
 - ggfortify: mutate_() 
 - ggguitar: filter_()
 - ggmuller: filter_()
 - glycanr: group_by_()
 - goldi: select_()
 - graphicalVAR: mutate_()
 - graphTweets: select_()
 - gt: group_by(.dots=)
 - highcharter: arrange_()
 - hurricaneexposure: mutate_()
 - huxtable: mutate_()
 - iadf: select_()
 - IAT: filter_()
 - idmodelr: group_by(.dots=)
 - ipeadatar: select_()
 - ipft: group_indices_()
 - iRF: select_()
 - kernelPhil: group_by_()
 - LAGOSNE: filter_()
 - Lahman: summarise_each()
 - lifelogr: suimmarise_()
 - lmeresampler: group_by_()
 - lookupTable: summarise_()
 - mase: select_()
 - matman: group_by(.dots=)
 - modelplotr: group_by_()
 - Momocs: mutate_()
 - mosaicModel: group_by_()
 - mtconnectR: arrange_()
 - ncdump: select_()
 - networkreporting: select_()
 - NobBS: group_by_()
 - nonmemica: arrange_()
 - nosoi: mutate_() 
 - omu: select_()
 - padr: group_by(.dots=)
 - PAMpal: select_()
 - panelr: mutate_()
 - photobiologyInOut: mutate_()
 - pkggraph: arrange_()
 - PKNCA: summarise_()
 - plinkQC: select_()
 - plotly: group_by_()
 - pmpp: arrange_()
 - pointblank: group_by(.dots=)
 - pollen: arrange_()
 - PPforest: filter_()
 - psycho: mutate_() 
 - psychonetrics: arrange_()
 - PupillometryR: summarise_()
 - quickpsy: group_by_()
 - rattle: unrelated
 - reclin: group_by_()
 - REddyProc: select_()
 - representr: group_by_()
 - rFIA: group_by(.dots=)
 - RNeXML: select_()
 - rollmatch: group_by_()
 - rties: group_by_()
 - rtimicropem: mutate_(), select_()
 - saeSim: arrange_()
 - sf: select_()
 - sfc: mutate_each()
 - simglm: group_by_()
 - simPH:  group_by(.dots=)
 - simTool: group_by(.dots=)
 - simts: filter_()
 - spatPomp: arrange_()
 - srvyr: se-deprecated documentation
 - starschemar: group_by(.dots=)
 - strand: group_by(.dots=)
 - surveybootstrap: group_indices_()
 - survminer: select_()
 - sweep: select_()
 - SWMPr: select_()
 - Tendril: rename_()
 - tidypredict: mutate_()
 - tidytree: mutate_(), filter_()
 - timelineS: group_by_()
 - trelliscopejs: group_by(.dots=)
 - trelliscopejs: filter_()
 - TwoRegression: summarise_()
 - useful: select_()
 - vpc: group_by_()
 - widyr: distinct_()
 - wrangle: arrange_()
 - xspliner: arrange_()
 - Zelig: group_by_()

**Comment by hadley** [comment]
Ok, definitely shouldn't do now. But maybe worth emailing those authors?

**Comment by romainfrancois** [comment]
cc @hadley I guess this is too much, and that probably means these are also still in use in many non package code too.

**Pull request closed without merging**
