### PR TITLE
sample_n and sample_frac handle lazy grouped data frames (#3380)

### PR DESCRIPTION
**Pull request by romainfrancois**

### CODE REVIEW

**Comment by krlmlr** [comment]
Is this superseded by #3527?

**Comment by romainfrancois** [comment]
I'll borrow the tests and see what happens

**Comment by romainfrancois** [comment]
✅

**Comment by krlmlr** [comment]
Did you mean to close this?

**Comment by romainfrancois** [comment]
yes, this Pr is now irrelevant because the only thing I need from it is the test, and I've moved it to #3527 

I understand about keeping issues open and let them close themselves when their pr are merged. IO thought this was different because that's a pr, and so closing this prematurely limits the chances of merging it when we don't need it.

**Comment by krlmlr** [comment]
Yes, my bad. Closing old PRs is good.

**Pull request closed without merging**
