### PR TITLE
Alter `n_distinct()` to only remove cases where all arguments are missing

### PR DESCRIPTION
**Pull request by DavisVaughan**

### CODE REVIEW

**Comment by romainfrancois** [comment]
Is this still going to take care of this issue: 

``` r
library(dplyr, warn.conflicts = FALSE)
 
tibble(y = 1) %>% 
  summarise(n = n_distinct(.data$y))
#> Error: `summarise()` argument `n` errored.
#> ℹ `n` is `n_distinct(.data$y)`.
#> x Column `y` not found in `.data`
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This breaks a few packages: confoundr, dexterMST, fgeo.analyze, ISRaD, strataG, xrf on revdeps.

**Comment by krlmlr** [comment]
I see this in this branch:

``` r
library(dplyr, warn.conflicts = FALSE)

tibble(y = 1) %>%
  summarise(n = n_distinct(.data$y))
#> # A tibble: 1 x 1
#>       n
#>   <int>
#> 1     1
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Do we need a test?

**Comment by romainfrancois** [comment]
Yes please :-)

**Comment by DavisVaughan** [comment]
@lionel- has convinced me that this is incorrect, and the current `n_distinct()` behavior is right. I'm adding `vec_complete_cases()` to vctrs, and then we can implement `n_distinct()` as:

```r
n_distinct <- function(..., na.rm = FALSE) {
  data <- list2(...)
  names(data) <- as.character(seq_along(data))
  
  size <- vec_size_common(!!!data)
  data <- vec_recycle_common(!!!data, .size = size)
  
  data <- new_data_frame(data, n = size)
  
  if (isTRUE(na.rm)) {
    data <- vec_slice(data, vec_complete_cases(data))
  }
  
  vec_unique_count(data)
}
```

This avoids any tibble issues with `.data$` (i.e. it works with CRAN tibble too)

Nevertheless, this PR wont be relevant, as it takes the wrong approach, so I'll close.

I'll do another PR once I have `vec_complete_cases()` finished

**Pull request closed without merging**
