### PR TITLE
Warn but support list columns in distinct()

### LINKED ISSUE #3226: distinct() throws unnecessary (?) error for list columns when .keep_all = TRUE
I don't think it is necessary to throw an error if a dataframe contains list columns but the list columns aren't used for uniqueness. At least when I tried out some quick examples it seemed to work when removing the line
`list_cols_error(.data, keep)` in `dis_vars()`.
If the behaviour is intended it seems to me that there is a test missing for it.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

data <- tibble(a = 1, b = list(1))
# distinct on non-list column: works as expected
distinct(data, a)
#> # A tibble: 1 x 1
#>       a
#>   <dbl>
#> 1  1.00

# distinct on list column: throws error as expected
distinct(data, b)
#> Error: distinct() does not support columns of type `list`

# distinct on non-list column: throws error but shouldn't?
distinct(data, a, .keep_all = TRUE)
#> Error: distinct() does not support columns of type `list`
```

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.0 (2017-04-21)
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       UTC                         
#>  date     2017-11-28
#> Packages -----------------------------------------------------------------
#>  package    * version    date       source                           
#>  assertthat   0.2.0      2017-04-11 CRAN (R 3.4.0)                   
#>  backports    1.1.1      2017-09-25 CRAN (R 3.4.2)                   
#>  base       * 3.4.0      2017-04-21 local                            
#>  bindr        0.1        2016-11-13 cran (@0.1)                      
#>  bindrcpp     0.2        2017-06-17 CRAN (R 3.4.0)                   
#>  cli          1.0.0      2017-11-05 CRAN (R 3.4.2)                   
#>  compiler     3.4.0      2017-04-21 local                            
#>  crayon       1.3.4      2017-11-22 Github (r-lib/crayon@b5221ab)    
#>  datasets   * 3.4.0      2017-04-21 local                            
#>  devtools     1.13.4     2017-11-09 CRAN (R 3.4.2)                   
#>  digest       0.6.12     2017-01-27 CRAN (R 3.4.0)                   
#>  dplyr      * 0.7.4.9000 2017-11-22 Github (tidyverse/dplyr@fc66342) 
#>  evaluate     0.10       2016-10-11 CRAN (R 3.4.0)                   
#>  glue         1.2.0      2017-10-29 CRAN (R 3.4.0)                   
#>  graphics   * 3.4.0      2017-04-21 local                            
#>  grDevices  * 3.4.0      2017-04-21 local                            
#>  htmltools    0.3.6      2017-04-28 CRAN (R 3.4.0)                   
#>  knitr        1.17       2017-08-10 CRAN (R 3.4.1)                   
#>  magrittr     1.5        2014-11-22 CRAN (R 3.4.0)                   
#>  memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                   
#>  methods    * 3.4.0      2017-04-21 local                            
#>  pillar       0.0.0.9000 2017-11-22 Github (r-lib/pillar@5a082e1)    
#>  pkgconfig    2.0.1      2017-03-21 cran (@2.0.1)                    
#>  purrr        0.2.4      2017-10-18 cran (@0.2.4)                    
#>  R6           2.2.2      2017-06-17 cran (@2.2.2)                    
#>  Rcpp         0.12.13    2017-09-28 cran (@0.12.13)                  
#>  rlang        0.1.4      2017-11-05 cran (@0.1.4)                    
#>  rmarkdown    1.8        2017-11-17 CRAN (R 3.4.2)                   
#>  rprojroot    1.2        2017-01-16 CRAN (R 3.4.0)                   
#>  stats      * 3.4.0      2017-04-21 local                            
#>  stringi      1.1.6      2017-11-17 CRAN (R 3.4.2)                   
#>  stringr      1.2.0      2017-02-18 CRAN (R 3.4.0)                   
#>  tibble       1.3.4.9003 2017-11-22 Github (tidyverse/tibble@60281b3)
#>  tidyselect   0.2.3      2017-11-06 CRAN (R 3.4.2)                   
#>  tools        3.4.0      2017-04-21 local                            
#>  utf8         1.1.0      2017-11-20 cran (@1.1.0)                    
#>  utils      * 3.4.0      2017-04-21 local                            
#>  withr        2.1.0      2017-11-01 cran (@2.1.0)                    
#>  yaml         2.1.14     2016-11-12 CRAN (R 3.4.0)
```

</details>

### PR DESCRIPTION
**Pull request by krlmlr**
Closes #3226.

### CODE REVIEW

**Comment by krlmlr** [comment]
@romainfrancois: I'm still interested in a review, but I need code from this branch now.

**Comment by romainfrancois** [comment]
Sure. I’ll look into it

**Comment by krlmlr** [comment]
Thanks. Maybe hash the list?

What do you mean by "a warning is weak"?

**Comment by romainfrancois** [comment]
Hashing perhaps yes, perhaps this is `vctrs` again. 

Not sure what I mean, but as a user, I'd prefer either that it works or that it did not (error).

**Comment by krlmlr** [comment]
I'd rather not break downstream dependencies over this, just make them very aware with the warning. If this was a new verb, of course it should be an error.

**Comment by romainfrancois** [comment]
Sure, I get your point. Perhaps this is enough until we find a way to make it work for real. 

```
> distinct( data.frame( x = I(list(1:3, seq(1L, 3L))) ))
        x
1 1, 2, 3
2 1, 2, 3
Warning message:
distinct() does not fully support columns of type `list`.
List elements are compared by reference, see ?distinct for details.
This affects the following columns:
- `x` 
```

I'd expect there are very few cases where this gives the right answer

**Comment by krlmlr** [comment]
I have a added two examples to `?distinct`.

**Pull request merged**
