### PR TITLE
Performance improvements for summarise()

### PR DESCRIPTION
**Pull request by romainfrancois**
I'm just opening this here to have a place for this conversation, so I can upload screenshots of profvis results.

### CODE REVIEW

**Comment by romainfrancois** [comment]
Using this code to study some baseline: 

```r
library(dplyr, warn.conflicts = FALSE)
df <- tibble(x = rnorm(1e6), g = sample(rep(1:1e4, 100))) %>% group_by(g)
profvis::profvis(for (i in 1:100) out <- summarise(df, a = +1))
```

The expression `+1` is so that "something" happens and has to be evaluated for each group, 10000 groups of size 100. For now the variables from the data are not touched by the expression, so their promise should be left untouched by `DataMask`

We start from: 

image

So attacking `DataMask$eval()` first : 

image

**Comment by romainfrancois** [comment]
Caching `mask$eval` before the loop

image

**Comment by romainfrancois** [comment]
Pushing the loop internally trims some overhead, this needs a callable `vctrs_is_vector()` though: https://github.com/r-lib/vctrs/pull/695

image

**Comment by romainfrancois** [comment]
Moving the `map_int(vec_size)` internally: 

image

**Comment by romainfrancois** [comment]
Using the `bench-mean.R` script, this is looking at `summarise(mean)` in various situations: 

 - master but using `.Internal(mean(.))` so that we don't pay for the dispatch
 - master using `mean()`
 - master using `length()` instead of `mean()` just so that we have some idea of the cost of all the slicing
 - 0.8.3 using `.Internal(mean()`
 - 0.8.3 using hybrid `mean()`
 - 0.8.3 using `mean()` not hybrid

Also varying the number of rows and groups: 

```
[summarise_performance] 156.6 MiB ❯ bench_mean(1e6, 10)
# A tibble: 6 x 7
  branch fun                      n ngroups   median mem_alloc  n_gc
  <chr>  <chr>                <dbl>   <dbl> <bch:tm> <bch:byt> <dbl>
1 master length             1000000      10   11.5ms    8.68MB     7
2 master .Internal(mean(.)) 1000000      10   13.9ms    8.68MB     6
3 master mean(.)            1000000      10   14.2ms     8.7MB     6
4 0.8.3  .Internal(mean(.)) 1000000      10     11ms    7.65MB     9
5 0.8.3  hybrid mean(.)     1000000      10   10.6ms   14.12KB     0
6 0.8.3  mean2(.)           1000000      10   10.7ms    7.67MB     9
[summarise_performance] 160.1 MiB ❯ bench_mean(1e6, 100000)
# A tibble: 6 x 7
  branch fun                      n ngroups   median mem_alloc  n_gc
  <chr>  <chr>                <dbl>   <dbl> <bch:tm> <bch:byt> <dbl>
1 master length             1000000  100000  388.9ms    4.86MB    13
2 master .Internal(mean(.)) 1000000  100000  384.5ms    5.25MB    13
3 master mean(.)            1000000  100000  656.1ms    5.27MB    12
4 0.8.3  .Internal(mean(.)) 1000000  100000  219.3ms     803KB     4
5 0.8.3  hybrid mean(.)     1000000  100000   19.7ms  795.42KB     0
6 0.8.3  mean2(.)           1000000  100000  507.3ms  825.73KB     8
[summarise_performance] 162.4 MiB ❯ 
[summarise_performance] 162.4 MiB ❯ bench_mean(1e7, 10)
# A tibble: 6 x 7
  branch fun                       n ngroups   median mem_alloc  n_gc
  <chr>  <chr>                 <dbl>   <dbl> <bch:tm> <bch:byt> <dbl>
1 master length             10000000      10   77.6ms    77.3MB     3
2 master .Internal(mean(.)) 10000000      10   96.8ms    77.3MB     3
3 master mean(.)            10000000      10   97.7ms    77.4MB     3
4 0.8.3  .Internal(mean(.)) 10000000      10  100.2ms    76.3MB     3
5 0.8.3  hybrid mean(.)     10000000      10  121.5ms    14.1KB     0
6 0.8.3  mean2(.)           10000000      10  106.1ms    76.3MB     3
[summarise_performance] 162.5 MiB ❯ bench_mean(1e7, 1000000)
# A tibble: 6 x 7
  branch fun                       n ngroups   median mem_alloc  n_gc
  <chr>  <chr>                 <dbl>   <dbl> <bch:tm> <bch:byt> <dbl>
1 master length             10000000 1000000    4.49s    39.2MB     9
2 master .Internal(mean(.)) 10000000 1000000    4.47s   43.01MB     9
3 master mean(.)            10000000 1000000    6.53s   43.03MB    15
4 0.8.3  .Internal(mean(.)) 10000000 1000000    2.16s    7.65MB     7
5 0.8.3  hybrid mean(.)     10000000 1000000  313.7ms    7.64MB     0
6 0.8.3  mean2(.)           10000000 1000000    5.07s    7.67MB    33
```

Seems that most of the time in the new approach is taken by generating all the chunks, that's also what `profvis` suggests: 

```r
library(profvis)
callr::r(function() {
  library(dplyr, warn.conflicts = FALSE)
  library(purrr)
  library(vctrs)

  df <- tibble(x = rnorm(1e6), y = rnorm(1e6), g = sample(rep(1:10, 1e5))) %>% group_by(g)
  profvis::profvis(for (i in 1:100) out <- summarise(df, a = .Internal(mean(x))))
})
```

image

hybrid evaluation from 0.8.3, which in that case does not need to materialize the chunks makes more sense when there are lots of groups. 

Generating all the chunks consumes a lot of memory

**Comment by hadley** [comment]
Given the latest benchmarks, I think it would be reasonable to finish this PR off and get it merged — I think you've captured most of the low hanging fruit, and it would be useful to get this into master. Let me know when it's review for me to review.

**Comment by romainfrancois** [comment]
Sure. We can always keep going in a separate pull request anyway. There are similar changes needed for `mutate()` and `filter()`.  

I'll make sure this passes and let you know.

**Pull request merged**
