### PR TITLE
Remove -Wall -Wextra warnings

### PR DESCRIPTION
**Pull request by krlmlr**
- Unused arguments
- One instance of potentialy wrong behavior detected

### CODE REVIEW

**Comment by lionel-** [comment]
do we really need to remove all warnings?

**Comment by krlmlr** [comment]
Yes.

**Comment by lionel-** [comment]
> Yes.

if you tell me why is that the case that we need to address esoteric warnings, I could add the relevant flags to my local builds and you wouldn't need to track warnings after I push code. These boost unused attributes etc seem to obscure the code without real benefit.

**Comment by krlmlr** [comment]
I agree with your last point, but that esoteric warning helped pinpoint a potential bug and unnecessarily complicated code.

There are other options:

- Define a shorter macro (e.g., `UNUSED`)
- Use the `(void)arg;` idiom
- Don't name arguments we don't use (e.g., `int func(SEXP)`)

In my g++ builds, I'm now using `-Wall -Wextra -pedantic`, and I hope to add `-Wconversion` soon; in addition, `-Werror` treats warnings as errors (they are easy to overlook otherwise) and `-Wfirst-error` aborts on first error (which is the only one relevant in many cases).

**Comment by lionel-** [comment]
I think I prefer unnaming the unused arguments.

**Comment by hadley** [comment]
I'd prefer unnaming the unused arguments too.

**Pull request merged**
