### PR TITLE
fix logo link typo in README

### PR DESCRIPTION
**Pull request by nathancday**
Added missing "/" in the logo link so it works properly.

### CODE REVIEW

**Comment by batpigandme** [comment]
Hi @nathancday,

Thanks for the fix. What versions of dplyr and roxygen2 are you running? As you can see from the [diffs](https://github.com/tidyverse/dplyr/pull/4220/files), there are a few things unrelated to the link fix that changed. Most of this is the rendering of Rmd ⇨ md, but there's a difference in the results of one of the examples that is unexpected.

**Comment by nathancday** [comment]
Yikes I see what you mean in the example, I have to admit I didn't really **read** the Rmd doc and figured the differences were just roxygen being roxygen and saying files differed after they were re-knitted.

I used `devtools::load_all()` to load the current github state of the pacakge (which did result it in re-compiling itself, but no errors that I could see). Maybe I should have used the CRAN version? Here it my `sessionInfo()`

```
sessionInfo(c("dplyr", "roxygen2"))
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
  [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
  character(0)

other attached packages:
  [1] dplyr_0.8.0.9002 roxygen2_6.1.1  

loaded via a namespace (and not attached):
  [1] Rcpp_1.0.0        rstudioapi_0.9.0  magrittr_1.5      usethis_1.4.0     devtools_2.0.1   
[6] grDevices_3.5.2   tidyselect_0.2.5  pkgload_1.0.2     R6_2.4.0          rlang_0.3.1      
[11] BH_1.69.0-1       tools_3.5.2       utils_3.5.2       pkgbuild_1.0.2    sessioninfo_1.1.1
[16] cli_1.0.1         plogr_0.2.0       withr_2.1.2.9000  stats_3.5.2       remotes_2.0.2    
[21] datasets_3.5.2    yaml_2.2.0        assertthat_0.2.0  digest_0.6.18     rprojroot_1.3-2  
[26] tibble_2.0.1      base_3.5.2        crayon_1.3.4      processx_3.2.1    purrr_0.3.0      
[31] callr_3.1.1       graphics_3.5.2    fs_1.2.6          ps_1.3.0          testthat_2.0.1   
[36] memoise_1.1.0     glue_1.3.0        pillar_1.3.1      compiler_3.5.2    methods_3.5.2    
[41] desc_1.2.0        backports_1.1.3   prettyunits_1.0.2 pkgconfig_2.0.2  
```

**Comment by batpigandme** [comment]
Thanks! I think you're right about roxygen (you have the right version — I can never remember which syntax is the newest one for markdown), let's ask @romainfrancois re. the versioning for the example there.

**Comment by romainfrancois** [comment]
I’ll attempt to have a look, but I’m off this week with limited non-parenting time.

**Comment by nathancday** [comment]
I was just playing around with `dplyr` versions and it looks the arrangement of `NA` values changed from 0.7.8 >>> 0.8.0. In the earlier they came last, so they were in the results of the [code chunk in question](https://github.com/tidyverse/dplyr/blob/88604406061231dcbdca79edf682765f1281be0a/README.Rmd#L96) but not shown in the first 5 rows. In the later the `NA` values come first, so you see them. It also looks like the last time the [md file was modified](https://github.com/tidyverse/dplyr/commit/f34f58710a682e0a54516c7436b73a2696702c7a) the same result, i.e. `NA`first, was existing, but was replaced with the "correct" result, i.e. `Droid` first. Just wanted to share, interested to see what the root cause of this is.

**Comment by romainfrancois** [comment]
That looks like a problem in `group_by()` I'll open a separate issue with this simpler reprex: 

``` r
library(dplyr, warn.conflicts = FALSE)

tbl <- tibble(
  x = c("apple", NA, "banana"), 
  y = 1:3
)
tbl %>% 
  group_by(x) %>% 
  group_data()
#> # A tibble: 3 x 2
#>   x      .rows    
#>   <chr>  <list>   
#> 1 <NA>   <int [1]>
#> 2 apple  <int [1]>
#> 3 banana <int [1]>
```

<sup>Created on 2019-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by romainfrancois** [comment]
Perhaps as a stop before we deal with this in #4227 we could update the example in the README, e.g. also filter by `mass` or something. 

Also, as you're here, can you also remove the new obsolete `Release candidate` section 🙏 ?

**Comment by nathancday** [comment]
I think I figured out the extra changes to README.md. I was getting a "handshake failed" error around the r-pkg button, and re-installing `pandoc` via `brew` (even tho it was the same version 2.6 🤔 ) seems to have fixed it.

**Comment by romainfrancois** [comment]
Thanks !!

**Pull request merged**
