### PR TITLE
Check with bionic instead of xenial

### PR DESCRIPTION
**Pull request by krlmlr**
xenial is EOL, currently RSQLite fails to install there (https://github.com/r-dbi/RSQLite/issues/378).

### CODE REVIEW

**Comment by romainfrancois** [comment]
Does this also need to be updated upstream in https://github.com/r-lib/usethis/blob/master/.github/workflows/R-CMD-check.yaml @jimhester ?

**Comment by jimhester** [comment]
That is not upstream, that is the workflow file just for usethis. The workflows are stored at https://github.com/r-lib/actions/tree/master/examples and they are all using 18.04 once 16.04 was EOL'd.

**Comment by romainfrancois** [comment]
Thanks.

**Comment by krlmlr** [comment]
Builds are failing on the main branch -- maybe invalidate the package cache?

**Pull request merged**
