### PR TITLE
remove old boost related defines that may no longer be needed.

### PR DESCRIPTION
**Pull request by romainfrancois**
`rhub` seems to be happy about this: 
https://builder.r-hub.io/status/dplyr_0.7.99.9000.tar.gz-a245d7e84f894bff857408eec6c49d31

I'll update when I get the results from `check_win_devel()` as well...

### CODE REVIEW

**Comment by lionel-** [comment]
IIRC these defines were added to avoid warnings with `-Wall -pedantic`. It looks like the rhub build doesn't use `-pedantic`.

**Comment by krlmlr** [comment]
Also with explicit C++98?

**Comment by romainfrancois** [comment]
Should probably investigate more, but perhaps boost took care of it...

**Comment by krlmlr** [comment]
Looks like I'm overly cautious here. I'm forcing C++98 for packages that don't declare C++11, haven't noticed anything strange with 968f4ef0.

**Pull request merged**
