### PR TITLE
Use private class for rows errors for now

### PR DESCRIPTION
**Pull request by krlmlr**
CC @lionel-.

### CODE REVIEW

**Comment by krlmlr** [comment]
Good catch!

**Comment by hadley** [comment]
Per our standard policy, we shouldn't even be throwing classed errors here.

**Comment by krlmlr** [comment]
I feel that's a step backward. Can we adapt the standard policy?

**Comment by lionel-** [comment]
It feels like there really are only two error classes here, `dplyr_error_rows_missing` and `dplyr_error_rows_duplicate`?

**Comment by krlmlr** [comment]
Sure, we can aggregate the error classes.

**Comment by lionel-** [comment]
It's probably best to just remove all the classes for now then, especially since testthat does not understand the `:::` separator yet.

**Comment by krlmlr** [comment]
Let's revisit later.

**Comment by lionel-** [comment]
I think we should either remove the classes or use triple colons.

**Comment by lionel-** [comment]
Or at least use the `dplyr_error_` namespace if we keep them in 1.0.

**Pull request closed without merging**
